openshift-kni/lifecycle-agent

HACKING.md
ibu-imager/README.md
ibu-imager/cmd/consts.go
ibu-imager/cmd/create.go
ibu-imager/internal/seedcreator/seedcreator.go
ibu-imager/internal/seedcreator/seedcreator_test.go

Remove hardcoded image tag `oneimage` and force the command line parameter to include the full refspec.
Example:
`ibu-imager create -r quay.io/someone/ibu-seed-image:mytag`

ibu-imager: Use full refspec for the remote repository

---

Dockerfile
ibu-imager/Dockerfile

This PR replaces Dockerhub's [golang](https://registry.hub.docker.com/layers/library/golang/1.19/images/sha256-1611d4f97c5ab666d3c123d72b3bb646dd12bbf7577dd1388fdb191d54cdf440?context=explore) base image with the Red Hat's [go-toolset](https://catalog.redhat.com/software/containers/ubi9/go-toolset/61e5c00b4ec9945c18787690?architecture=amd64&image=653020421d14c242647051fc&container-tabs=overview) one. 
The latter is a bit bigger `449.3 MB` vs `361.55 MB`, but it's scanned for vulnerabilities and it's actively being maintained by RH.

Use RH go-toolset instead of dockerhub golang base image

---

Dockerfile
ibu-imager/Dockerfile

This PR reverts build images to dockerhub, but updates them to go 1.20, as both projects are on go 1.20.

Revert back to dockerhub go registry but go 1.20

---

ibu-imager/seedcreator/seedcreator.go

If crio is down, `systemctl is-active` ends with status code 3, so we need to capture that exit code and continue execution
/cc @leo8a 
/cc @tsorya

Fix check condition for crio down

---

ibu-imager/cmd/consts.go
ibu-imager/cmd/create.go
ibu-imager/installation_configuration_files/conf/installation-configuration.env
ibu-imager/installation_configuration_files/scripts/installation-configuration.sh
ibu-imager/installation_configuration_files/services/installation-configuration.service
ibu-imager/installation_configuration_files/services/prepare-installation-configuration.service

This file can be used to configure on-the-fly the variables used / needed in the scripts called by the systemd units like  installation-configuration.service.

[imager] Add envFile to dynamically configure vars in systemd units

---

bundle/manifests/lifecycle-agent-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
config/rbac/role.yaml
internal/clusterconfig/clusterconfig.go
internal/clusterconfig/clusterconfig_test.go

Adding clusterversion watch to rbac, delete ingress as we don't need it currently

Adding clusterversion watch to rbac, delete ingress as we don't need it currently

---

HACKING.md
ibu-imager/README.md
ibu-imager/cmd/create.go
ibu-imager/ops/ops.go
ibu-imager/seedcreator/seedcreator.go
utils/utils.go

This validation ensures that the seed SNO cluster can be re-certified during the IBU workflow later on without errors. Additionally, it forces the expiration of the certificates in the seed SNO cluster.

[imager] Add recert force-expire towards seed cluster 

---

Dockerfile
ibu-imager/Dockerfile

This PR replaces the dockerhub Go 1.20 base images with the [RH go-toolset 1.20](https://catalog.redhat.com/software/containers/ubi9/go-toolset/61e5c00b4ec9945c18787690?architecture=amd64&image=654387c17ea05ac1dd92a58a). It also adds source code layers explicitly, in order to leverage caching where possible.
Related PRs: 
- https://github.com/openshift-kni/lifecycle-agent/pull/39
- https://github.com/openshift-kni/lifecycle-agent/pull/43

Move to RH go-toolset 1.20 base images

---

hack/generate-dnsmasq-site-policy-section.sh

Added helper script to generate a section that can be added to an SNO site-policy to override the 50-master-dnsmasq-configuration from the assisted installer, until the necessary changes are available in ACM.
/cc @tsorya @alosadagrande

Add helper script for generating dnsmasq workaround site-policy

---

bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
config/manager/manager.yaml

setting `hostPID: true` in the pod allows us to use `nsenter` within the pod

Add hostPID to LCA pod

---

.gitattributes
bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
config/rbac/role.yaml
ibu-imager/clusterinfo/clusterinfo.go
ibu-imager/installation_configuration_files/scripts/installation-configuration.sh
ibu-imager/installation_configuration_files/scripts/prepare-installation-configuration.sh
ibu-imager/seedcreator/seedcreator.go
internal/bindata/prepSetupStateroot.sh
internal/clusterconfig/clusterconfig.go
internal/clusterconfig/clusterconfig_test.go
internal/clusterconfig/networkconfig.go
internal/clusterconfig/networkconfig_test.go
internal/clusterconfig/recert.go
internal/generated/zz_generated.bindata.go
utils/utils.go

Create recert configuration file in LCA: 
1. Adding host  ip to clusterInfo in order to use it for recert config
2. Moving recert configuration creation to LCA in order to remove this logic from installation script that will only run recert without decision making
3. LCA will create recert_config.json that will be provided to recert command
4. Installation script cleanup and impromevents
5. Moving get node ip to kube command

Create recert configuration file in LCA 

---

Dockerfile
ibu-imager/common/consts.go
ibu-imager/ops/ops.go
ibu-imager/seedcreator/seedcreator.go
internal/clusterconfig/recert.go

Having recert validation steps in ops will allow us to use the same steps in different workflows (e.g., seed image creation and cleanup) of the ibu-imager.

[Imager] Add recert steps to ops package

---

bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
config/rbac/role.yaml
internal/clusterconfig/clusterconfig.go
internal/clusterconfig/clusterconfig_test.go

This change is part of the cluster reconfiguration, which takes place after spinning up the seed image onto the target SNO. Cluster reconfiguration supports a predefined set of the original SNO cluster's configuration, e.g. IDMS, pull-secret, network configuration.
Specifically, this change addresses fetcing the [OCP cluster-wide proxy ](https://docs.openshift.com/container-platform/4.14/networking/enable-cluster-wide-proxy.html)  of the original SNO and creating the respective JSON manifest to be [applied](https://github.com/openshift-kni/lifecycle-agent/blob/main/ibu-imager/installation_configuration_files/scripts/installation-configuration.sh#L199) alongside the rest of the cluster reconfiguration manifests.
> The canonical name for the Proxy object is `cluster`. As per the respective …

MGMT-16155: Copy  cluster-wide proxy from original SNO to upgraded one

---

internal/clusterconfig/clusterconfig.go

This PR removes the original `pull-secret`s metadata from the respective manifest, which is applied as part of the cluster reconfiguration. 
This change fixes the following `installation-configuration.service` failure:
```shell
journalctl -f -u installation-configuration.service
Nov 17 13:54:21 sno1 installation-configuration.sh[64556]: Error from server (Conflict): error when applying patch:
Nov 17 13:54:21 sno1 installation-configuration.sh[64556]: {"metadata":{"creationTimestamp":"2023-11-16T14:58:57Z","managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:data":{".":{},"f:.dockerconfigjson":{}},"f:type":{}},"manager":"cluster-bootstrap","operation":"Update","time":"2023-11-16T14:58:57Z"}],"resourceVersion":"1876","uid":"9849789b-d0f4-45fe-8108-3b690fec728b"}}
Nov …
```

Remove redundant metadata from pull-secret in cluster reconfiguration

---

HACKING.md
bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/ibu_controller.go
controllers/upgrade_handlers.go
internal/backuprestore/backup.go
internal/backuprestore/backup_test.go
internal/backuprestore/common.go
internal/backuprestore/restore_test.go
internal/extramanifest/extramanifest.go

- init code for upgrade prepivot
- Call and backup and extra-manifest as needed and moved some of the functions to upgradeHandler
- No requeue-ing when an error is caught
- an error msg for when ibu name is not what's expected
- CRs to quickly deploy minIO and other support CRs+doc to work with backup in HACKING.md
- include RBAC for deletebackuprequests

init upgradehandler (pre-pivot) and cleanup

---

HACKING.md
internal/precache/constants.go
internal/precache/helper.go
main/main.go
main/precache-workload/main.go

This PR contains changes to allow a developer to configure pre-caching to `best-effort`, i.e. continue with Prep stage when the pre-caching job failed to pull one or more images.
/cc @donpenney @browsell

CNF-10428: Add functionality to allow best-effort for pre-caching

---

controllers/upgrade_handlers.go
ibu-imager/seedcreator/seedcreator.go
internal/clusterconfig/clusterconfig.go
internal/clusterconfig/clusterconfig_test.go
internal/recert/recert.go
utils/utils.go

I found the old name to be a bit confusing

Cosmetic: rename `WriteToFile` function to `MarshalToFile`

---

Makefile
ibu-imager/README.md
ibu-imager/cmd/create.go
ibu-imager/cmd/restore.go
ibu-imager/cmd/root.go
ibu-imager/seedcreator/seedcreator.go
ibu-imager/seedrestoration/seedcleanup.go

This exposes the cleanup workflow via a new restore cmd. Particularly handy when re-running such workflow is needed (e.g., after workflow failure).
Related to #79.

[imager] Add restore cmd to expose cleanup workflow

---

bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
config/manifests/bases/lifecycle-agent.clusterserviceversion.yaml

Added some initial description info to improve what it is currently shown from the console catalog hub. This needs to be updated with product final info, but we can adopt this in the meantime.
Before
After

Add initial description info to LCA bundle

---

.golangci.yml
controllers/prep_handlers.go
controllers/seedgen_controller.go
ibu-imager/seedcreator/seedcreator.go
ibu-imager/seedrestoration/seedcleanup.go
internal/backuprestore/backup.go
internal/backuprestore/restore.go
internal/backuprestore/restore_test.go
main/precache-workload/main.go

Enabled the errorlint and loggercheck plugins, along with configuring the revive plugin to check for error messages that start with a capital letter.

Enable additional golangci-lint plugins

---

ibu-imager/seedcreator/seedcreator.go

In some cases when there is a large number of /etc files to save, the list of files gets truncated resulting in an incomplete arhive which later impacts the upgrade process as installation-configuration systemd service cannot start.
This change removes the xargs usage and uses tar's files-from option instead which seems to overcome the issues when having a large number of files.

Update tar usage when saving /etc files

---

ibu-imager/clusterinfo/clusterinfo.go
ibu-imager/postpivot/postpivot.go
internal/clusterconfig/clusterconfig_test.go
internal/recert/recert.go

This PR adds the following changes:
- adds `hostname` to `ClusterInfo`, in order to be able to replace the seed hostname with the target hostname in certs (in this PR) and static pod manifests (in a future PR)
- adds recert configuration params to replace the seed hostname with the target hostname in the `kubelet-client.pem` and `kubelet-server.pem`, with the goal of having those certs ready to go and skip the kubelet CSR generation (and hence the manual approval of the kubelet CSRs) during the post-pivot flow
- removes the post-pivot step of the kubelet CSR approvals 
According to how kubelet behaves, see [here](https://github.com/kubernetes/kubernetes/blob/930022cf267c2e0269fbd9be4be3fd83448e6419/pkg/kubelet/certificate/kubelet.go#L97-L103) and …

OCPEDGE-664: Pregenerate kubelet certs to skip post-pivot CSR approvals

---

controllers/prep_handlers.go
internal/prep/prep.go
internal/prep/prep_test.go

Prep did not work if version string had multiple dashes. For example: 4.15.0-0.nightly-2023-12-04-223539
Now instead of splitting deploymentId by '-' and using the second item we use the last item

Fix prep failing when version had multiple dashes

---

bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
config/rbac/role.yaml
internal/healthcheck/healthcheck.go

This update includes the following:
- change client.Client parameter to client.Reader, to support non-cached client in early init function
- bug fix for ClusterOperator condition check
- add checks for ClusterOperator Progressing=false and Degraded=false
- add Node "Ready" check, as well as node-role labels
- add ClusterVersion Available=true check
- update health check polling interval to 30 seconds

Update health checks

---

ibu-imager/installation_configuration_files/scripts/prepare-installation-configuration.sh
ibu-imager/ops/ops.go
ibu-imager/postpivot/postpivot.go
internal/recert/recert.go

[MGMT-16227](https://issues.redhat.com//browse/MGMT-16227): cleanup etcd keys with seed hostname in them
Fixing preconfiguration script to match IBI logic
In case certs dir was not created, we should not fail recert config creation but rather not to provice key rules

MGMT-16227: cleanup etcd keys with seed hostname in them and small fixes for IBI process

---

ibu-imager/ops/execute.go
main/main.go

logging output of every `ChrootExecutor.Execute` is cluttering the log,
log the output of commands explicitly if needed by calling `ExecuteWithLiveLogger`
Also removed unused logger

    Add ExecuteWithLiveLogger and stop logging commands output by default

---

controllers/upgrade_handlers.go
controllers/utils/conditions.go
internal/backuprestore/backup.go
internal/backuprestore/backup_test.go
internal/backuprestore/common.go
internal/backuprestore/restore.go
internal/backuprestore/restore_test.go
internal/common/utils.go
internal/extramanifest/extramanifest.go
internal/extramanifest/extramanifest_test.go

The directories that store the manifests will be cleaned up once each recovery has completed.
i.e., /opt/du-extra-manifests
/opt/OADP/secret
/opt/OADP/dpa
/opt/OADP/veleroRestore
Upgrade will fail when there's issue with creation of extramanifest, recovery of OADP configuration and failed restore CRs.

Upgrade post pivot with extra manifest apply and OADP restore

---

controllers/ibu_controller.go
controllers/idle_handlers.go
controllers/idle_handlers_test.go
internal/backuprestore/backup.go
internal/backuprestore/common.go
internal/ostreeclient/mock_ostreeclient.go
internal/ostreeclient/ostreeclient.go

- Add function to remove all unbooted stateroots
- Try to run all cleanup functions even if one of them returns an error
- Run backup cleanup and delete OADP operator in abort and finalize

Add handleFinalize and perform backup cleanups

---

controllers/ibu_controller.go
controllers/idle_handlers.go
controllers/prep_handlers.go
controllers/utils/conditions.go
controllers/utils/constants.go
go.mod
internal/precache/constants.go
internal/precache/precache.go
main/main.go

The progress file used to track and facilitate the various sub-stages of the prep-stage is removed. A new prep-stage worker goroutine is used instead.
Support is added to abort the prep-stage during any of the intermediate sub-steps (i.e. pulling the seed image, setting up the stateroot, precaching images).
/cc @jc-rh @browsell @sudomakeinstall2

CNF-10412: Remove progress file from the prep-handler

---

ibu-imager/installation_configuration_files/scripts/prepare-installation-configuration.sh

Previously this was checking for the existence of /opt/openshift which would always be present at this point as it was created earlier in the script. Instead this should check for the presence of the configuration directory which will only be present if we don't need to copy data from the ISO.
Relates to https://issues.redhat.com/browse/MGMT-16394
cc @tsorya

Fix condition for mounting config ISO

---

controllers/upgrade_handlers.go
docs/backuprestore-with-oadp.md
internal/backuprestore/backup.go
internal/backuprestore/backup_test.go
internal/backuprestore/common.go
internal/backuprestore/restore.go
internal/backuprestore/restore_test.go
internal/extramanifest/extramanifest.go
utils/utils.go

- Fail the upgrade if more than one DPA found
-  Wait until DPA is reconciled before checking storage backend and do not exit the storage check immediately if no storages found
- Use utils function to read/write resource from/to file
- Use hostPath from common
- Re-organize some logs

Some changes to backup&restore plugin

---

controllers/seedgen_controller.go

In a totally disconn env, the recert image may be mirrored to the local (private) registry as well.

seedgen: Fix recert podman pull for disconn registries

---

controllers/ibu_controller.go
controllers/prep_handlers.go
controllers/seedgen_controller.go
ibu-imager/clusterinfo/clusterinfo.go
ibu-imager/postpivot/postpivot.go
ibu-imager/seedcreator/seedcreator.go
internal/clusterconfig/clusterconfig.go
internal/clusterconfig/clusterconfig_test.go
internal/common/consts.go
internal/prep/prep.go
main/main.go
utils/client_helper.go

InfoClient is a wrapper to runtimeclient.Client, we can remove
it and use runtimeclient.Client directly. Its functions are moved
to utils/client_helper.go
Doing this also enables us to use BackupCeritificates in the LCA

Remove InfoClient and move its functions to utils/client_helper.go

---

controllers/prep_handlers.go

Flowing directly into the error string without a colon is confusing,
especially if the error message itself starts with something like
"failed to..." then it reads "Prep failed due to failed to..."

Cosmetic: Change prep failure message

---

hack/summarize-ibu.sh

`PrepCompleted` is irrelevant in the case of prep failure
Before:
```
Image:   quay.io/otuchfel/ostbackup:seed
Version: 4.13.5
Stage:   Prep
Status:
Prep failed:
Time:    2023-12-18T14:35:26Z
Reason:  Failed
Message: Prep failed
```
After:
```
Image:   quay.io/otuchfel/ostbackup:seed
Version: 4.13.5
Stage:   Prep
Status:
Prep failed:
Time:    2023-12-18T14:35:26Z
Reason:  Failed
Message: Prep failed due to failed to extract ostree.tgz:
gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
: exit status 2
```

summarize-ibu prep failure should display `PrepInProgress`

---

HACKING.md
controllers/ibu_controller.go
controllers/rollback_handlers.go
controllers/seedgen_controller.go
controllers/upgrade_handlers.go
controllers/utils/conditions.go
hack/summarize-ibu.sh
ibu-imager/ostreeclient/mock_rpmostreeclient.go
ibu-imager/ostreeclient/rpmostreeclient.go
internal/ostreeclient/mock_ostreeclient.go
internal/ostreeclient/ostreeclient.go
main/main.go

Added use of "ostree admin set-default" feature, if enabled, to manage setting the desired next-boot deployment.
This feature also allows for the introduction of rollback support.

Add support for rollback and ostree admin set-default

---

controllers/rollback_handlers.go
controllers/upgrade_handlers.go

Updated reboot command to use systemd-run to launch the reboot as a transitory service-unit job, rather than directly running the reboot command. This allows for the LCA pod to cleanly shut down on receiving the SIGTERM, rather than hanging on the running reboot command.

Update reboot command to avoid hanging

---

internal/precache/workload/pullImages.go

The precache handler checks images to see whether they already exist in container-storage prior to pulling. In the case of tagged images, however, this means the image could be stale, as the tag may have been updated in the registry.
This update modifies the precache handler to never skip pulling tagged images. If the tag has not been updated, the layers should not get downloaded, only the manifest, so the pull should be quick.

precaching: Always pull tagged images

---

controllers/prep_handlers.go
ibu-imager/clusterinfo/clusterinfo.go
ibu-imager/postpivot/postpivot.go
utils/client_helper.go
utils/utils.go

1. If seed has mirror registry and cluster not, try to override
2. If cluster has mirror registry and seed not verify if seeds registry is part of sources in icsps and idms and if it is don't override
3. If cluster has mirror registry and seed regsitry is not part of sources try to override seeds registry

Mirror registry : Adding verification if we should override mirror registry or not

---

controllers/ibu_controller.go
internal/backuprestore/common.go
internal/backuprestore/mocks/mock_backuprestore.go

Before starting the prep stage, validate IBU spec for OADP configmaps first. If the validation fails, the prep stage will be failed.

Add IBU spec validation for OADP before prep

---

OWNERS

Any PR changing any cluster-configuration API related files will
automatically get a `cluster-config-api-changed` label.
The cluster configuration API is consumed by external projects (e.g. the
project currently named
[cluster-relocation-service](https://github.com/openshift/cluster-relocation-service))
so changes to this API should not be done casually, they have to be
explicitly thought out and ideally non-breaking.
This change along with a [corresponding PR in openshift/release](https://github.com/openshift/release/pull/47213) to gate
PRs that have this label (until removed as an act of acknowledgment)
using tide config will ensure that people developing, testing and
reviewing for the IBU use case also take the IBI use case (which
consumes the same API) into account
An alternative …

Cluster config API diff to trigger label

---

controllers/prep_handlers.go
ibu-imager/seedcreator/seedcreator.go
internal/common/consts.go

IBU reconciler now has a `checkSeedImageCompatibility` method that
checks if the seed image is compatible with the current version of the
lifecycle-agent. It does so by inspecting the OCI image's labels and
checking if the specified format version equals the hard-coded one that
this version of the lifecycle agent expects. That format version is set
by the imager during the image build process, and is only manually
bumped by developers when the image format changes in a way that is
incompatible with previous versions of the lifecycle-agent.

Seed image format version OCI image label

---

controllers/prep_handlers.go
ibu-imager/ostreeclient/mock_rpmostreeclient.go
ibu-imager/ostreeclient/rpmostreeclient.go
internal/ostreeclient/ostreeclient.go

In an IBU where both releases have the same underlying rhcos image, the parent commit of the deployment has unique commit IDs (due to import from seed), but the same checksum. When the new deployment is created, the original parent commit is getting pruned as a result.
In order to avoid this pruning, this update includes the following changes:
- Add the "--no-prune" option to the "ostree admin deploy" command
- Add a call to "rpm-ostree cleanup -b" to update the base refs

Handle IBU with no rhcos delta

---

api/seedgenerator/v1alpha1/types.go
api/v1alpha1/types.go
bundle/manifests/lca.openshift.io_imagebasedupgrades.yaml
bundle/manifests/lca.openshift.io_seedgenerators.yaml
config/crd/bases/lca.openshift.io_imagebasedupgrades.yaml
config/crd/bases/lca.openshift.io_seedgenerators.yaml
controllers/ibu_controller.go
controllers/rollback_handlers.go
controllers/seedgen_controller.go
controllers/upgrade_handlers.go
controllers/upgrade_handlers_test.go
controllers/utils/conditions.go
main/main.go

Updates include:
- Include Stage in IBU display
- Include State and Details in SeedGen display
- Make seedgen spec immutable and only handle Create events
- Add mutex to prevent IBU and SeedGen reconcilers from running at the same time
- Delete IBU CR prior to generating seed image, so it is not included in the seed
- Update Rollback states and progress messages to provide more useful feedback for user
- Improve seedgen error handling and reporting
/cc @browsell @jc-rh

Improve Rollback and Seedgen status reporting and error handling

---

docs/backuprestore-with-oadp.md
go.mod
internal/backuprestore/backup.go
internal/backuprestore/backup_test.go
internal/backuprestore/common.go
internal/backuprestore/common_test.go
main/main.go
vendor/k8s.io/client-go/dynamic/fake/simple.go
vendor/modules.txt

OADP backup doesn't support backing up specific CRs by object names, and
the way to scope/filter backup specific resources is by using label
selector.
This commit provides a method for users to pass in the specific
resources, and LCA will apply the label to those resources internally in
order for the backup CR to pick up them only.
The resources could be passed using the
`lca.openshift.io/apply-label` annotation. The value should be a list of comma
separated objects in "group/version/resource/name" format for cluster-scoped
resources or "group/version/resource/namespace/name" format for namespace-scoped
resources, and it should be attached to the related Backup CR.
By defining this annotation, ther user indicates a desire to scope to
those resources only. LCA will parse the annotations, …

CNF-10755: Support labeling specific resources for backup filtering

---

api/seedreconfig/seedreconfig.go
internal/clusterconfig/clusterconfig.go

This field is not used on reconfiguration process and currently useful only for seed info

Remove unused field MirrorRegistryConfigured from SeedReconfiguration

---

Makefile
ibu-imager/installation_configuration_files/scripts/prepare-installation-configuration.sh
ibu-imager/postpivot/postpivot.go
ibu-imager/postpivot/postpivot_test.go

[MGMT-16601](https://issues.redhat.com//browse/MGMT-16601): allow installation without providing host ip in advance
In case host ip was not provided in manifest.json post-pivot configuration will start manually nodeip service, wait till it creates primary-ip file and read ip from it.
After getting ip it will create dnsmasq and dispatcher script override file and restart NM with dnsmasq

MGMT-16601: allow installation without providing host ip in advance

---

api/v1alpha1/types.go
bundle/manifests/lca.openshift.io_imagebasedupgrades.yaml
config/crd/bases/lca.openshift.io_imagebasedupgrades.yaml
controllers/prep_handlers.go
main/main.go

Condition.reason represent the state better than condition.type
Also:
- Remove precache summary from status messages
- Fix typo in main

Use `condition.reason` instead of `condition.type` as state in printercolumns

---

api/seedreconfig/seedreconfig.go
lca-cli/postpivot/postpivot.go
lca-cli/postpivot/postpivot_test.go

[MGMT-16559](https://issues.redhat.com//browse/MGMT-16559): Support NMState config
Adding new api field RawNMStateConfig that allows user to provide raw
nmstate yaml file that will be applied on the node with nmstatectl apply
command

MGMT-16559: Support NMState config 

---

hack/golangci-lint.sh
hack/shellcheck.sh

The ci-operator image appears to be ignoring its git config for safe.directory, causing git commands run during the ci-job to fail with 'dubious ownership' error. Until this issue is resolved, avoid git commands in the linter scripts.
Unfortunately, this means that the check-git-tree.sh script isn't able to check the git status. As a result, it's possible for commits with stale generated code files to be missed, where normally this check would catch such issues. Developers will need to manually run 'make ci-job' prior to posting PRs as a safety check.

Workaround for ci-operator git command issue in linter scripts

---

HACKING.md
internal/common/consts.go
lca-cli/README.md

The `:latest` tag of the recert image is not stable, it contains changes
from the `main` branch. We should default to the `:v0` tag instead which
we merge into less often.

Use recert stable tag

---

hack/golangci-lint.sh
hack/shellcheck.sh

Reverts openshift-kni/lifecycle-agent#251
CI fix for 4.14:
https://github.com/openshift-eng/ocp-build-data/pull/4268

Revert "Workaround for ci-operator git command issue in linter scripts"

---

controllers/ibu_controller.go
controllers/ibu_controller_test.go

update CR status and requeue immediately after stage transition so that in-progress status is visible properly.

Fix late update of in-progress status

---

api/seedreconfig/seedreconfig.go
internal/clusterconfig/clusterconfig.go
internal/clusterconfig/clusterconfig_test.go
internal/common/consts.go
lca-cli/postpivot/postpivot.go
lca-cli/postpivot/postpivot_test.go
utils/utils.go

IBU/I will set pull secret in struct and post pivot will create pull-secret secret that will be applied with all the manifests whenever
cluster will be up
Flow:
1. We will move seed pull secret aside, write new pull secret to
/var/lib/kubelet/config.json.
2. After api is up and images were pulled, we will write back seed pull
secret in order for MCO to be happy
3. After it we will apply new pull secret to cluster

MGMT-15783: moving pull secret to seed reconfiguration struct.

---

internal/recert/recert.go

This change leverages recert's latest OCP post-process [hostname](https://github.com/rh-ecosystem-edge/recert/pull/82) feature, which makes OCP's control-plane cluster operators (i.e. etcd, kube-apiserver, kube-controller-manager, kube-scheduler) happy, so that the latter won't trigger additional revisions. Thus reducing the time OCP needs to stabilize after recert.

Add recert hostname arg to skip control-plane revision triggers

---

api/seedreconfig/seedreconfig.go
internal/clusterconfig/clusterconfig.go
internal/clusterconfig/clusterconfig_test.go
internal/recert/recert.go
utils/client_helper.go

Solves [MGMT-15731](https://issues.redhat.com//browse/MGMT-15731)
Users of OCP expect the default kubeadmin password generated during
installation time to keep working even after an IBU.
To achieve that, LCA will have to copy the password hash from the
kube-system/kubeadmin secret in the original SNO into the
`SeedReconfiguration` struct so it can be set in the equivalent secret
in the new SNO.
Note that not all clusters that we will be upgrading will have such
password, as OCP encourages people, for security reasons, to disable
this password by deleting the secret as outlined here:
https://docs.openshift.com/container-platform/4.14/authentication/remove-kubeadmin.html
In case no such secret exists, LCA will ensure that the secret will
simply be deleted in the new SNO.
The secret hash …

Copy the kubeadmin password from original SNO

---

internal/recert/recert.go
lca-cli/postpivot/postpivot.go

Similar to b6c5db194b205dd86e2227b630907b92f597b724 but for IP instead of hostname
This change leverages recert's latest OCP post-process IP feature, which makes OCP's control-plane cluster operators (i.e. etcd, kube-apiserver, authentication, etc) happy, so that they won't trigger additional revisions. Thus reducing the time OCP needs to stabilize after recert.
For more details please check here:
- https://github.com/rh-ecosystem-edge/recert/pull/89

Add recert IP arg to skip control-plane revision triggers

---

controllers/seedgen_controller.go
controllers/utils/constants.go
internal/common/consts.go
lca-cli/seedcreator/seedcreator.go
main/main.go
utils/utils.go

We shouldn't be distributing the pull-secret of seed clusters. This cleans up the seed cluster of its pull-secret before seed creation to avoid unwanted distribution of this secret.
Also, added a commit to restore the original pull-secret in the seed cluster as soon as it gets back from seed creation for the cluster operators needing it.

CNF-11033: Delete pull secret from seed image

---

lca-cli/postpivot/postpivot.go
lca-cli/postpivot/postpivot_test.go

[MGMT-16652](https://issues.redhat.com//browse/MGMT-16652): Change configuration ISO label from relocation-config to cluster-config
Currently we will support old and new label for backward compatibility.
Fixing typo in function name

MGMT-16652: Change configuration ISO label from relocation-config to cluster-config

---

lca-cli/seedcreator/seedcreator.go
utils/utils.go

Removes the duplication of the recert image from the `containers.list` in seed images. As a result, it also reduces an extra operation while pre-cachingin IBU.
The recert image was already added to the node (and hence included in the `containers.list`) before by the seedgen CR.

Add recert image to containers.list only if not exists

---

internal/recert/recert.go

Right now post-pivot recert fails because this lack of hash causes the
pre-pivot expiration recert to delete the secret, which must not be
deleted.
See [MGMT-16801](https://issues.redhat.com//browse/MGMT-16801) for full future solution, but for now to unblock IBU
upgrades let's just place a placeholder hash in there.
Until the full solution is implemented, seeds will still have their
kubeadmin broken following an image generation.

Temporary workaround for password bug

---

lca-cli/postpivot/postpivot.go

In disconnected environments, post-pivot fails pulling the recert image with below error.
```
Feb 08 11:41:17 zt-sno2.inbound.vz.bos2.lab lca-cli[2609]: time="2024-02-08 11:41:17" level=info msg="pulling recert image"
Feb 08 11:41:17 zt-sno2.inbound.vz.bos2.lab lca-cli[2609]: time="2024-02-08 11:41:17" level=info msg="Executing podman with args [pull jumphost.inbound.vz.bos2.lab:8443/edge-infrastructure/recert:v0]"
Feb 08 11:45:20 zt-sno2.inbound.vz.bos2.lab podman[6040]: 2024-02-08 11:41:17.963436474 +0000 UTC m=+0.078100691 image pull  jumphost.inbound.vz.bos2.lab:8443/edge-infrastructure/recert:v0
Feb 08 11:45:20 zt-sno2.inbound.vz.bos2.lab lca-cli[2609]: time="2024-02-08 11:45:20" level=warning msg="failed to pull recert image, will retry, err: Trying to pull …
```

Fix post-pivot for disconn envs

---

controllers/idle_handlers.go
controllers/idle_handlers_test.go

If a deployment fails there could be a stateroot directory under `/ostree/deploy`. This stateroot will not be listed in rpm-ostree. This commit will remove such stateroots.

CNF-11185: Remove undeployed stateroots in finalize

---

api/seedreconfig/seedreconfig.go
lca-cli/postpivot/postpivot.go
lca-cli/postpivot/postpivot_test.go

[MGMT-16652](https://issues.redhat.com//browse/MGMT-16652): make configuration label part of seed reconfiguration api package as consts

MGMT-16652: make configuration label part of seed reconfiguration api package as consts

---

internal/precache/workload/pullImages.go
lca-cli/cmd/ibi.go
lca-cli/ibi-preparation/ibipreparation.go
main/precache-workload/main.go

[MGMT-16764](https://issues.redhat.com//browse/MGMT-16764): creating one function for precache and precache validation
[MGMT-16764](https://issues.redhat.com//browse/MGMT-16764): Add pre-caching modes to ibi command in LCA
Adding disable precaching and best-effort flags

MGMT-16764: Add pre-caching modes to ibi command in LCA

---

controllers/upgrade_handlers.go
controllers/upgrade_handlers_test.go
internal/common/utils.go

[OCPBUGS-29120](https://issues.redhat.com/browse/OCPBUGS-29120)
The oadp configmap should have been validated at prep stage but it may be a rare case where the configmap is deleted/changed after prep, so for any configmap issues that appear in the upgrade stage, we fail the upgrade. Also, for identical configmaps defined in spec, we only process them once. 
/cc @browsell @donpenney @jc-rh

Fail upgrade if any OADP configmap issues detected at upgrade stage

---

controllers/ibu_controller.go
controllers/idle_handlers.go
controllers/idle_handlers_test.go
controllers/utils/constants.go

If finalize or abort fails, ibu trasitions into finalizeFailed and
abortFailed states respectively.
```
status:
conditions:
- message: failed to cleanup backups. Perform cleanup manually then
add lca.openshift.io/manualCleanupDone
annotation to ibu CR to transition back to Idle
observedGeneration: 5
reason: AbortFailed
status: "False"
type: Idle
```
User should perform cleanup manually in these states. After manual
cleanup user should add 'lca.openshift.io/manualCleanupDone' annotation
to IBU CR.
```
kind: ImageBasedUpgrade
metadata:
annotations:
lca.openshit.io/manualCleanupDone: ""
```
Upon observing this annotation IBU will remove the annotations and runs
abort/finalize. If successful ibu transitions back to idle state.

CNF-11136: Add handleFinalizeFailure and handleAbortFailure

---

docs/backuprestore-with-oadp.md
internal/backuprestore/backup.go
internal/backuprestore/backup_test.go
internal/backuprestore/common.go
internal/backuprestore/common_test.go

Before this commit the scope of resources to be backed up using apply-backup label was cluster wide. So each individual backup resource made a backup of every resource it matched with.
Changing the value of label selector to the name of backup CR fixes this issue.
/cc @Missxiaoguo @browsell

Limit scope of backup apply label to one backup

---

internal/recert/recert.go
lca-cli/postpivot/postpivot.go
lca-cli/postpivot/postpivot_test.go
lca-cli/seedcreator/seedcreator.go

Post pivot will override the config.json in order to be able to pull recert image but recert will override all other places
Depends on https://github.com/rh-ecosystem-edge/recert/pull/100/files

MGMT-16873: Change pull secret as part of recert reconfiguration

---

controllers/seedgen_controller.go

Updated the seedgen reconciler system validation tests to include a check whether the "ostree admin set-default" feature is available, introduced in 4.14.7 and required to support IBU rollbacks.

Reject seedgen request if required ostree feature not present

---

bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/seedgen_controller.go

Removing machine-configs on seedcreation that are not used by mcp

MGMT-16968: Remove old rendered machine-configs from seed

---

bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
config/manifests/bases/lifecycle-agent.clusterserviceversion.yaml

This is a manual cherry-pick of https://github.com/openshift-kni/lifecycle-agent/pull/346
(we had some conflicts with the version, hence the manual cherry-pick - we kept the 4.15.0 version in the bundle)
/assign donpenney @rauhersu

[release-4.15] Fix lca bundle with workload.openshift.io/allowed annotation

---

HACKING.md
bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/ibu_controller.go
controllers/seedgen_controller.go
docs/seed-image-generation.md

Due to the potential issues stemming from ACM automatically re-importing the cluster, the support for hubKubeconfig and LCA deletion/restoration of the ManagedCluster CR had been dropped. The seedgen system validation now verifies that the cluster is not being actively managed by ACM prior to starting seed image generation, by checking for the klusterlets CRD. If present, this indicates ACM is managing the cluster, and the seedgen request is rejected.

CNF-11452: seedgen: Remove hubKubeconfig and hub interaction

---

docs/backuprestore-with-oadp.md

Related to #339 which I unintentionally closed. Sorry about that.
- Documentation update about the apply-label annotation.
- Documentation update about removing a pull-secret from open-cluster-management-agent ns which can cause the klusterlet backup example to fail.
cc/ @Missxiaoguo @donpenney

[doc] Clarifies backup documentation with OADP

---

api/v1alpha1/types.go
bundle/manifests/lca.openshift.io_imagebasedupgrades.yaml
config/crd/bases/lca.openshift.io_imagebasedupgrades.yaml

If the user provides a negative value for initMonitorTimeoutSeconds, it will be rejected when validating the IBU spec.

OCPBUGS-29483: Ensure initMonitorTimeoutSeconds positive values only

---

ib-cli/README.md
ib-cli/cmd/createiso.go
ib-cli/installationiso/data/ibi-butane.template
ib-cli/installationiso/data/install-rhcos-and-restore-seed.sh
ib-cli/installationiso/installationiso.go
ib-cli/installationiso/installationiso_test.go

Set as draft until https://github.com/openshift/assisted-service/pull/6005 or https://github.com/openshift/assisted-installer/pull/787 get to an openshift release

MGMT-16687: IBI use separate partition for /var/lib/containers

---

controllers/prep_handlers.go
internal/ostreeclient/mock_ostreeclient.go
internal/ostreeclient/ostreeclient.go
internal/prep/prep.go

In an IBU where both releases have the same underlying rhcos image, the parent commit of the deployment has unique commit IDs (due to import from seed), but the same checksum. This previously caused a failure after creating the deployment, which was resolved with: https://github.com/openshift-kni/lifecycle-agent/pull/203/commits
The fix required two changes:
- Add the "--no-prune" option to the "ostree admin deploy" command
- Add a call to "rpm-ostree cleanup -b" to update the base refs
Code restructuring in a later update moved the "rpm-ostree cleanup -b" call later in the workflow, inadvertently leading to the no-delta IBU failure reoccurring.
This update moves the cleanup step into the function calling "ostree admin deploy", with a clarifying comment explaining that it must immediately …

OCPBUGS-30063: Restore fix for IBU with no rhcos delta

---

internal/prep/prep.go

In the case where we're doing an IBU to a release with the same rhcos base image on a cluster that has previously been upgraded via IBU, we end up with the exact same set of boot loader config options in the deployments for both the old and new stateroots. This causes a problem for ostree, which is using the set of config options when comparing deployments to determine whether the boot loader entries need to be updated. When we're swapping deployments in order to pivot to the new release, the deployment boot serials get reassigned, however, as the deployments are in separate stateroots. Without also updating the boot loader entries, ostree ends up unable to correlate these entries with the boot links it has now swapped.
In order to avoid this issue, this update adds a karg to the new …

OCPBUGS-30063: Add version info to kargs for deploy in IBU

---

lca-cli/postpivot/postpivot.go

The machineconfig manifests generated by postpivot for updating the ssh keys were missing a filename extension, so were ignored by the oc apply command that applies the manifests directory. As a result, the 99-master-ssh and 99-worker-ssh machineconfigs were not being updated as expected. Adding the .json extension to the filenames resolves the issue.

postpivot: Fix ssh key machineconfig filenames

---

bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
config/rbac/role.yaml
go.mod
internal/clusterconfig/clusterconfig.go
internal/clusterconfig/clusterconfig_test.go

LCA should preserve the user-defined catalog sources 
This change will fetch the catalog sources pre-reboot, filter out the default catalog sources, and add the user-defined catalog sources as as extra manifests that will get applied post-reboot (before the application restore starts)

MGMT-17115: Save the custom catalog sources as extra manifests

---

controllers/seedgen_controller.go
internal/common/consts.go

If the seedgen CR does not define a specific recert image to use, check for the RELATED_IMAGE_RECERT_IMAGE environment variable. If set, use this as the default recert image. If not, fall back to the defined const.

CNF-11641: seedgen: Use RELATED_IMAGE_RECERT_IMAGE, if available

---

bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/ibu_controller.go
controllers/idle_handlers.go
controllers/prep_handlers.go
internal/precache/constants.go
internal/precache/helper.go
internal/precache/helper_test.go
internal/precache/precache.go
internal/precache/precache_test.go
main/main.go

Currently when a precache job is launched, reconcile is requested after an arbitrary amount of time. During the reconcile wait time the system could be in any state and we can not let the user know about it immediately if an event occurs such as when the job is done.
This is fixed by taking ownership of precache job using IBU cr (OwnerReferences). Now reconcile will be triggered as soon as job updates and system is checked to see if desired state has been reached to complete prep

CNF-11187: Reconcile when precache job updates

---

controllers/seedgen_controller.go
internal/common/consts.go

This is a manual cherry-pick of https://github.com/openshift-kni/lifecycle-agent/pull/388
/cc @browsell

[release-4.15] CNF-11641: seedgen: Use RELATED_IMAGE_RECERT_IMAGE, if available

---

.snyk
internal/backuprestore/restore.go
utils/crypto_dir.go
utils/utils.go

Fix remaining errors from https://github.com/openshift/release/pull/49688
The dot file was regenerated with the following
```
snyk ignore --file-path='vendor/**' --file-path-group='global'   
snyk ignore --file-path='**/*_test.go' --file-path-group='global'
```

CNF-11561: fix non-vendor snyk errors

---

ib-cli/installationiso/data/install-rhcos-and-restore-seed.sh

This change fixes an issue where the partition for local container storage already existed bfore writing the IBI ISO to disk:
~~~
Mar 13 11:32:32 localhost.localdomain install-rhcos-and-restore-seed.sh[2380]: Information: Moved requested sector from 853816974 to 853815296 in
Mar 13 11:32:32 localhost.localdomain install-rhcos-and-restore-seed.sh[2380]: order to align on 2048-sector boundaries.
Mar 13 11:32:32 localhost.localdomain install-rhcos-and-restore-seed.sh[2380]: Setting name!
Mar 13 11:32:32 localhost.localdomain install-rhcos-and-restore-seed.sh[2380]: partNum is 4
Mar 13 11:32:32 localhost.localdomain install-rhcos-and-restore-seed.sh[2380]: The operation has completed successfully.
Mar 13 11:32:32 localhost.localdomain kernel:  sda: sda1 sda2 sda3 sda4 sda5
Mar 13 11:32:32 …

Adds force in IBI flow to format containers partition if already existed

---

controllers/idle_handlers.go
internal/backuprestore/backup.go
internal/backuprestore/common.go
internal/backuprestore/mocks/mock_backuprestore.go

When facing network issues with the S3 storage backed, the user might need to also have automatic cleanup for the DeleteBackupRequests CRs that are leftover.

Add automatic cleanup for DeleteBackupRequests CRs when manualCleanUp annotation is set

---

internal/extramanifest/extramanifest.go
internal/extramanifest/extramanifest_test.go

Extra manifests should not contain anything that will trigger a reboot
as this would result in not meeting the KPI downtime requirement.
ExtraManifest validation will raise an error if there is MachineConfig
in extramanifests

CNF-11186: Raise validation error if there is a MachineConfig in extramanifests

---

HACKING.md

Update HACKING.md  with warning and recommendations regarding mirroring the recert image to ensure you have the same recert image being used during seed generation and post-pivot

MGMT-16819: Use the same recert image across seed generation and post-pivot

---

controllers/prep_handlers.go
internal/backuprestore/backup.go
internal/backuprestore/common.go
internal/backuprestore/mocks/mock_backuprestore.go

If the target cluster is reinstalled before cleaning up any previous Backups from the object storage, OADP may sync those stale Backup CRs back to this cluster, even though they are labeled with a different `clusterID`.
Handling those stale Backups early during the `Prep` stage would save the time required to delete those (via `DeleteBackupRequest` CR with OADP) from the `Upgrade` stage.
/cc @Missxiaoguo @jc-rh @browsell

OCPBUGS-30190: Cleanup stale Backups during Prep stage

---

internal/backuprestore/backup.go

This fixes the `CleanupStaleBackups` function for when there aren't Backups in the cluster. If the `getBackup` call returns `nil`, it now continues to the next one, avoiding any possible panic.
/cc @browsell @Missxiaoguo

OCPBUGS-30190: Improve CleanupStaleBackups function

---

controllers/idle_handlers.go
internal/backuprestore/backup.go
internal/backuprestore/backup_test.go
internal/backuprestore/common.go
internal/backuprestore/mocks/mock_backuprestore.go

Instead of creating deletebackuprequest for each backup and then wait for the backups to be deleted, poll the deletebackuprequest CRs themselves and wait for them to be processed and log the error list if there is any.
After that check all the backups are deleted.

CNF-11524: Log error list of deletebackuprequest

---

internal/backuprestore/backup.go
internal/backuprestore/backup_test.go
internal/backuprestore/common.go
internal/backuprestore/restore.go
internal/backuprestore/restore_test.go
internal/common/consts.go
internal/common/manifest_helpers.go
internal/common/manifest_helpers_test.go
internal/extramanifest/extramanifest.go
internal/extramanifest/extramanifest_test.go
utils/utils.go
utils/utils_test.go

Sort, group by and apply extra manifests with respect to `apply-wave`
annotation
Refactor sort, group by and load grouped manifests to use generics to
remove code duplications
Signed-off-by: Saeid Askari <saskari@redhat.com>

CNF-11236: Apply extra manifests in the order specified by the `apply-wave` annotation

---

controllers/upgrade_handlers.go
controllers/upgrade_handlers_test.go
docs/backuprestore-with-oadp.md
internal/backuprestore/backup.go
internal/backuprestore/backup_test.go
internal/backuprestore/common.go
internal/backuprestore/restore.go
internal/backuprestore/restore_test.go

If the target cluster is reinstalled before cleaning up any previous `Backups` from the object storage, OADP may sync those stale `Backup` CRs back to this cluster, even though they are labeled with a different `clusterID`.
This piece handles those stale backups during the `Upgrade` phase, basically we added a check to use only those `Backup` / `Restore` resources that matches the `clusterID` of the target cluster. Additionally, we also incorporated the `CleanupStaleBackups` function during this stage (for the case when any `Backup` is arbitrarily / unexpectedly changed between `Prep` and `Upgrade` stages).
Signed-off-by: Leonardo Ochoa-Aday [lochoa@redhat.com](mailto:lochoa@redhat.com)
/cc @Missxiaoguo @jc-rh @browsell

OCPBUGS-30190: Handle stale Backups during Upgrade stage

---

lca-cli/ops/ops.go
lca-cli/seedcreator/seedcreator.go

Store the backup kubeadmin hash file in the BackupCertsDir, so it wont make it to the seed image
/cc @omertuc

Do not store kubeadmin hash in seed image

---

lca-cli/ops/ops.go

This log is missing the command name, you could only see the args

Include command name in log

---

lca-cli/postpivot/postpivot.go

OCPBUGS-31896: Moving set of sshkey before network manipulations in order to allow ssh connection in case something will go wrong with network config but ip will exist

OCPBUGS-31896: Moving set of sshkey before network manipulations

---

internal/healthcheck/healthcheck.go
internal/healthcheck/healthcheck_test.go

The CSV status phase "Succeeded" represents a succeeded CSV. The reason why it's succeeded doesn't matter. 
It's not possible that it's "Succeeded" but with an "unsucceeded" reason.

OCPBUGS-32040: Check status phase only for CSV healthcheck

---

docs/must-gather.md
internal/recert/recert.go
must-gather/collection-scripts/gather_lca

Logs should now be independent. New files
- recert-seed-creation-summary.yaml
- recert-seed-restoration-summary.yaml
Also suppressing excessive console logs + and excluding `/etc/sriov-operator` when rsyncing `/etc`
/cc @omertuc @donpenney @browsell

CNF-11624: fix log paths and collect recert-seed-creation-summary and recert-seed-restoration-summary

---

api/seedreconfig/seedreconfig.go
lca-cli/postpivot/postpivot.go
lca-cli/postpivot/postpivot_test.go

[MGMT-17364](https://issues.redhat.com//browse/MGMT-17364): Allow providing subnet for IBI installation
Adding new api field MachineNetwork it will be used to set nodeip hint that will point nodeip-configuration to the right ip

MGMT-17364: Allow providing subnet for IBI installation

---

HACKING.md
api/v1alpha1/types.go
bundle/manifests/lca.openshift.io_imagebasedupgrades.yaml
bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
config/crd/bases/lca.openshift.io_imagebasedupgrades.yaml
config/manifests/bases/lifecycle-agent.clusterserviceversion.yaml
controllers/upgrade_handlers.go
docs/image-based-upgrade.md
internal/common/consts.go
internal/reboot/reboot.go

The autoRollback configs are now done using annotations and must only be configured for debug purposes.

CNF-11876: remove autoRollback config params from spec (except InitMonitorTimeoutSeconds) and use annotations instead

---

controllers/prep_handlers.go

250e53fba735c245be768ef09fadd5080b4c531f introduced a regression which caused older seed images to stop working. The regression was caused by backwards compatibility code having an inverse condition.
This commit fixes that

Fix invalid condition

---

api/seedgenerator/v1alpha1/types.go
api/v1alpha1/types.go
bundle/manifests/lca.openshift.io_imagebasedupgrades.yaml
bundle/manifests/lca.openshift.io_seedgenerators.yaml
config/crd/bases/lca.openshift.io_imagebasedupgrades.yaml
config/crd/bases/lca.openshift.io_seedgenerators.yaml

Adds some validations to ensure `seedImage` and `recertImage` fields in seedgen are valid strings. As well as `.spec.SeedImageRef.Image` in the IBU CR.
/cc @donpenney @browsell @achuzhoy

OCPBUGS-32294: Add string validations for some fields in seedgen and IBU specs

---

controllers/upgrade_handlers.go
controllers/upgrade_handlers_test.go
internal/backuprestore/backup.go
internal/backuprestore/backup_test.go
internal/backuprestore/common.go
internal/backuprestore/restore.go
internal/backuprestore/restore_test.go
internal/healthcheck/healthcheck.go
internal/healthcheck/healthcheck_test.go

When oadp DPA is applied and reconciled, check the connectivity of the storage backend. Sometimes it may simply require more time to come up or be due to a temporary connection issue. Moving the storage backend check into healthcheck could help to ensure the connectivity of storage at each stage.
/cc @donpenney @browsell

CNF-11930: Move oadp storage backend connection check to healthcheck

---

internal/common/utils.go
lca-cli/postpivot/postpivot.go

Retry applying the manifest when it fails due to API server not responding. The initmonitor will eventually time out if it's not recovered.
/cc @browsell @donpenney

CNF-11754: Retry apply of manifest on retriable failure

---

internal/recert/recert.go

Recert supports generating a summary of what it did. The summary
contains sensitive information. Recert supports both a regular summary
with sensitive info and a clean summary with sensitive info removed.
LCA must-gather collects recert summaries and includes them in the
must-gather
LCA used the regular summary option instead of the clean one, this
caused sensitive information to appear in LCA must-gathers
The `summary_file` option leaks private keys, and should not be used
outside debugging / testing purposes.
Change LCA to use the clean summary file option instead, so that
sensitive information does not get included in must-gathers
Solves OCPBUGS-32420

Only use `summary_file_clean` recert option

---

bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
config/rbac/role.yaml
internal/extramanifest/policy.go

A non fatal log shows up during pre pivot
```
E0417 21:11:51.138232   58444 reflector.go:147] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers.go:208: Failed to watch *v1.Policy: unknown (get policies.policy.open-cluster-management.io)
``` 
Controller-runtime client automatically starts a watch on resources that's been previously fetched with`Get`...this is should suppress it
/cc @Missxiaoguo @jc-rh @donpenney

fix policy watch error (Failed to watch *v1.Policy: unknown)

---

bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/upgrade_handlers.go

Removes the SR-IOV workaround from the upgrade handler.
I've kept the support for gathering info about SR-IOV operator in the must-gather thou, if this needs to be also removed, just let me know.
/cc @donpenney @browsell

OCPBUGS-32377: [IBU] Remove SR-IOV workaround from upgrade handler

---

controllers/upgrade_handlers.go
controllers/upgrade_handlers_test.go
docs/image-based-upgrade.md
internal/backuprestore/backup.go
internal/backuprestore/common.go
internal/extramanifest/extramanifest.go
internal/extramanifest/extramanifest_test.go
internal/extramanifest/policy.go

It was required to label the manifests with the full release ocp version defined in spec.seedImageRef.version.
It's too much effort for user to label the manifests for each z-stream upgrade , especially when there may be no changes.
Update to match either full release version, X.Y.Z or X.Y
The utility function to load resources from a directory requires sub directories,
update the directory structure of policy manifests to follow that pattern.
/cc @browsell @jc-rh @donpenney

CNF-11934: Change the matching versions of target-ocp-version label

---

bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/idle_handlers.go
controllers/upgrade_handlers.go
controllers/upgrade_handlers_test.go
docs/backuprestore-with-oadp.md
docs/image-based-upgrade.md
docs/troubleshooting.md
internal/backuprestore/backup.go
internal/backuprestore/backup_test.go
internal/backuprestore/common.go
internal/backuprestore/mocks/mock_backuprestore.go

Adds support for LVMS in LCA.
The implemented workflow is as follows:
- pre-pivot: LCA patches to `Retain` all PVs created by LVMS and with a Reclaim Policy of `Delete`.
- post-pivot: LCA restores back to `Delete` the Reclaim Policy of all PVs created by LVMS.
- rollback -> idle: LCA restores back to `Delete` the Reclaim Policy of all PVs previously patched.
Also added docs and a couple of entries to the troubleshooting guide.
/cc @browsell @Missxiaoguo @donpenney @jakobmoellerdev

OCPBUGS-32206: [IBU] LVMS volume contents not restored 

---

controllers/prep_handlers.go
controllers/upgrade_handlers.go
controllers/upgrade_handlers_test.go
docs/image-based-upgrade.md
internal/extramanifest/extramanifest.go
internal/extramanifest/extramanifest_test.go
internal/extramanifest/mocks/mock_extramanifest.go
internal/extramanifest/policy.go

When "lca.openshift.io/target-ocp-version-manifest-count" annotation is provided in the IBU, verify that the labeled manifests found in the policies matches the number of expected manifests in both Prep and Upgrade stages
/cc @browsell @jc-rh @pixelsoccupied @donpenney

CNF-10889: Validate the count of manifests extracted from policies

---

Makefile

The operator-sdk --index-image option is not required for the operator-sdk run bundle command.

Update bundle-run target in Makefile

---

internal/backuprestore/backup.go
internal/backuprestore/common.go
internal/backuprestore/common_test.go

Adds a check to the CleanupStaleBackups function to detect if a localVolume is specified in the resources in Backup CRs, and ignores its cleanup.
Also, refactors a bit the ValidateOadpConfigmaps function to reduce time complexity.
/cc @browsell @Missxiaoguo @donpenney

OCPBUGS-32939: [IBU] Add localVolume presence check in CleanupStaleBackups

---

controllers/ibu_controller.go
internal/backuprestore/backup.go

An issue occurs during the prep and upgrade stages when cleaning up stale backup CRs. The check detects that the deleteBackupRequest is not found, but its associated backup CR still exists, causing the stage to fail. It can be easily reproduced in the prep stage. The fact is the backup has actually been deleted, but it still exists at the time  when querying the backup This is due to a very small race condition in the deleteBackupRequest check, where it queries the deleteBackupRequest CR immediately after its creation, and the updates haven't been synced in the cache yet. As a result, the deleteBackupRequest CR is not found on the first check, and LCA continues checking the backup CR, which is actually being deleted. Setting the immediate parameter to false for the poll function makes it …

OCPBUGS-33065: deletionBackupRequests check update

---

internal/clusterconfig/clusterconfig_test.go
lca-cli/postpivot/postpivot.go
lca-cli/postpivot/postpivot_test.go
lca-cli/seedclusterinfo/seedclusterinfo.go
utils/client_helper.go

[MGMT-16807](https://issues.redhat.com//browse/MGMT-16807): set correct no proxy and proxyStatus
We should create NoProxy and proxyStatus exactly same way as cluster network operator. 
Took CNO function and made it match lca. 
Added service and cluster networks to seedInfo

MGMT-16807: set correct no proxy and proxyStatus

---

ib-cli/cmd/createiso.go
ib-cli/installationiso/data/ibi-butane.template
ib-cli/installationiso/data/install-rhcos-and-restore-seed.sh
ib-cli/installationiso/installationiso.go
ib-cli/installationiso/installationiso_test.go
lca-cli/cmd/ibi.go
lca-cli/ibi-preparation/ibipreparation.go
lca-cli/ops/mock_ops.go
lca-cli/ops/ops.go

[MGMT-17586](https://issues.redhat.com//browse/MGMT-17586): [IBI] Shutdown the node after the RHCOS image is written to the disk.
In order to run shutdown command after chroot we need to unchroot adding such option as helper function.

MGMT-17586: [IBI] Shutdown the node after the RHCOS image is written to the disk

---

internal/common/consts.go
lca-cli/ops/ops.go
lca-cli/seedcreator/seedcreator.go

In order to maintain file capabilities, which are extended attributes, the --xattrs tar command option is required.

OCPBUGS-33182: Include acls and xattrs in tar commands for seed image

---

internal/prep/prep.go

LCA is responsible for constructing the kernel arguments for the new
stateroot. Right now it only copies the KernelArguments field of the
MachineConfig, but it should also look at the `FIPS` field and make
sure to add the `fips=1` kernel argument when it's true
Solves [OCPBUGS-29360](https://issues.redhat.com/browse/OCPBUGS-29360)

Pass `fips=1` flag to new stateroot if MC is fips

---

internal/backuprestore/backup.go
internal/backuprestore/common.go

Adds an error check for when the backup label is not found or any other temporary API issues. This aims to reduce the noise provoked when the label is tried to be removed and it doesn't exist. 
/cc @donpenney @browsell @Missxiaoguo

OCPBUGS-33012: [IBU] Add presence check for backup label in patchObj

---

internal/backuprestore/backup.go
internal/backuprestore/common.go
internal/backuprestore/common_test.go

Dropping commit [094f0d5](https://github.com/openshift-kni/lifecycle-agent/commit/094f0d50e13302a4edcea62769ca520353196264) since it is not needed anymore. There was a race in the [ensureBackupsDeleted](https://github.com/openshift-kni/lifecycle-agent/blob/main/internal/backuprestore/backup.go#L566-L590) function - fixed in [PR#471](https://github.com/openshift-kni/lifecycle-agent/pull/471/files) - that was provoking [OCPBUGS-32939](https://issues.redhat.com//browse/OCPBUGS-32939).
Moreover, a check to ignore existing "localvolume" Backup CRs during `Prep` stage should not be added, given that LCA will try to create a Backup CR with the same name and this could provoke issues during the pre-pivot step.
```
{"name":"upgrade"}, "namespace": "", "name": "upgrade", "reconcileID": …
```

OCPBUGS-32939: Drop "Add check for localVolume presence in CleanupStaleBackups"

---

ib-cli/installationiso/data/install-rhcos-and-restore-seed.sh
internal/common/utils.go
internal/prep/prep.go
lca-cli/cmd/ibi.go
lca-cli/ibi-preparation/ibipreparation.go
lca-cli/seedcreator/seedcreator.go

In order to remove dependency between ibi installer and lca image, we want to use lca-cli that is part of seed image. for this we are going to copy lca-cli from seed image and run it as binary. Changing ibi installation script to copy binary from seed image. Adding lca-cli as part of seed image without need to untar var. Small changes in order to allow ibipreparation logic to run in as binary still leaving an option to run it as container

MGMT-17746: Move using lca-cli as binary in IBI iso

---

lca-cli/initmonitor/initmonitor.go

The LCA init monitor watchdog is enabled in the seed image and will
start in both IBU and IBI, but only IBU will create the auto-rollback
configuration file. In an IBI, the file will not exist, so the watchdog
will not run. The watchdog should shut down silently in that case, but
the current error check is failing due to the error being wrapped.
Changing the check to use errors.Is will ensure the wrapped error is
checked, and the watchdog now exits without logs when the configuration
file does not exist.

OCPBUGS-32488: Fix config file error check in init monitor watchdog

---

internal/common/consts.go
internal/extramanifest/extramanifest.go
internal/extramanifest/extramanifest_test.go
internal/extramanifest/merge.go
internal/extramanifest/policy.go

- Introduced a new annotation for manifest apply type (replace vs merge) and implemented the apply/merge logic
- Updated manifest extraction logic to capture CRs under musthave as well as mustonlyhave and annotate them accordingly

OCPBUGS-33178: Support replace/merge when applying extra manifests

---

.github/pull_request_template.md

As the scale of the project grows, it is important to encourage documenting changes, while at the same time making it easier for reviewers to understand the changes being made.
Since each person often works on their own areas of the project, and since we have contributors from many different locations and timezones, we don't often get a chance of having technical discussions in real time, so it's getting harder to keep track and review changes by other people. We often have to infer the intent of the changes from the code itself / vague and outdated Jira tickets that were written well before the implementation.
We also often make changes without much planning or a design document, making the code the only source of truth, which can sometimes be a bit cryptic and will make it difficult for …

Introduce PR/Commit message template

---

bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
config/rbac/role.yaml
internal/clusterconfig/lvmconfig.go
internal/clusterconfig/lvmconfig_test.go

The storage classes that are being used in the localvolumes should be exported and restored along with localvolumes during post-pivot as well.

OCPBUGS-33535: export associated storage classes when exporting localvolumes

---

ib-cli/installationiso/data/ibi-butane.template
ib-cli/installationiso/data/install-rhcos-and-restore-seed.sh

OCPBUGS-33536: [IBI] install-rhcos-and-restore-seed.service fails the first time it starts
We are taking lca-cli from seed image and sometimes it can fail. Adding dependency for this service on network-online and adding retry to image pull part

OCPBUGS-33536: [IBI] install-rhcos-and-restore-seed.service fails the first time it starts

---

.testcoverage.yml
Makefile
README.md
controllers/upgrade_handlers_test.go
internal/backuprestore/restore_test.go
internal/extramanifest/extramanifest_test.go
internal/extramanifest/policy_test.go
pkg/dependencymagnet/doc.go

This PR proposes the following:
- Updates README.md with some badges. 
- Fixes some misspell, ineffassign and gofmt recommendations provided by the goreportcard.
- Adds code-coverage target to Makefile and a config file, these could be used (e.g., in the ci-job or in local by devs) at any moment.
/cc @donpenney

CNF-12712: Add badges and code-coverage targets

---

controllers/idle_handlers.go
controllers/prep_handlers.go
docs/image-based-upgrade.md
internal/common/utils.go
internal/prep/prep_stateroot_setup_job.go
lca-cli/cmd/ibuStaterootSetup.go

This PR aims to handle the case when Stateroot setup job may be in-progress and an unexpected  SIGTERM is received (e.g moving to Idle while Prep in progress).
The solution is broken into to two parts:
k8s: 
- The max wait time before a SIGKILL is sent is determined with TerminationGracePeriodSeconds. This is now set to 60 secs (default 30)
- PreStop lifecycle handler was investigated but not useful in our case. Generally it's used to delay the container from getting SIGTERM and in the meantime k8s does other housekeeping tasks (e.g de-registering Ingress) to avoid any race conditions.
Handler in the code: 
- Every app is expected to have it's own signal handler. In this case if seed image is present we allow the rest of the stateroot setup to go through by sleeping at most time set with …

CNF-12656: Handle SIGTERM for stateroot setup job

---

lca-cli/ops/mock_ops.go
lca-cli/ops/ops.go
lca-cli/postpivot/postpivot.go
lca-cli/postpivot/postpivot_test.go

1. We should block localhost as hostname
2. In case hostname was not provided as part of seed reconfiguration we should use current node hostname
3. Hostname should be set with hostnamectl command rather than with /etc/hostname file in order to be changed immediately

MGMT-17828: LCA should allow reconfiguration if hostname wasn't provided

---

ib-cli/installationiso/data/ibi-butane.template

https://github.com/openshift-kni/lifecycle-agent/commit/e20c260d00eb2c9b03a6b174151615b884c5c85f broke the ability to set unexisting selinux contexts to files introduced by https://github.com/openshift-kni/lifecycle-agent/commit/f26ae70d96640cf7b974b5d5ad23ee2db967d228
Just change the script to `install_exec_t` context before running it
/cc @tsorya 
/cc @donpenney

OCPBUGS-33786 - Fix SELinux issues in IBI when running outside of a container

---

controllers/prep_handlers.go
lca-cli/cmd/create.go
lca-cli/seedclusterinfo/seedclusterinfo.go
lca-cli/seedcreator/seedcreator.go
utils/client_helper.go

Solves [MGMT-17748](https://issues.redhat.com//browse/MGMT-17748)
LCA recently added support for upgrading of FIPS-enabled clusters (see
commit 82460adaf5f3709f707b7f1126f7f180a32ed587).
The current implementation does not enforce FIPS compatibility between
the seed image and the cluster being upgraded. This can lead to issues
when the seed image has FIPS enabled but the cluster being upgraded does
not, or vice versa.
Add a check for FIPS compatibility between the seed image and the cluster
being upgraded.
- Add a new field `HasFIPS` to the `SeedClusterInfo` struct to store
whether the seed image has FIPS enabled or not. This field is set
based on the value of the `FIPS` field in the `MachineConfig` object
referenced by the `machineconfiguration.openshift.io/currentConfig`
label of the …

Enforce FIPS compatibility

---

lca-cli/postpivot/postpivot.go

OCPBUGS-34010: In case proxy status was set there is no reason to update proxy in post pivot phase (IBU flow)
In IBU flow we take proxy and proxy status from upgraded cluster and there is no need to update those values in post-pivot
failure in proxy installation

OCPBUGS-34010: In case proxy status was set there is no reason to update proxy in post pivot phase (IBU flow)

---

bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
config/rbac/role.yaml
controllers/idle_handlers.go
controllers/prep_handlers.go
controllers/upgrade_handlers.go
controllers/upgrade_handlers_test.go
docs/image-based-upgrade.md
internal/extramanifest/extramanifest.go
internal/extramanifest/extramanifest_test.go
internal/extramanifest/mocks/mock_extramanifest.go

LCA performs Kubernetes Dry-run to validate the manifests included in the extraManifests configmaps. Any invalid/webhook badRequest type of error returned from dry-run fails the Prep stage and blocks the upgrade.
Kubernetes Dry-run sends requests to API server, where the server processes the request as if it were real, but without acutally making any modifications to the actual resources. As all API requests are single-resource requests, dryrun doesn't work for resources that depends on eariler resources that are not persisted in the cluster. For example, in a multi-object manifest that includes namespace A and resource A created within the namespace A. Running a dry-run on resource returns the namespace not found error.
The extra manifests are configurations intented to be applied to the …

OCPBUGS-33275: extramanifest configmaps validation update

---

controllers/idle_handlers.go
internal/backuprestore/backup.go
internal/backuprestore/common.go
internal/backuprestore/mocks/mock_backuprestore.go

LCA may incorrectly try to delete OADP resources if configured with proxy even though no OADP is not present/installed 
e.g error
```
2024-05-23T21:04:01Z	ERROR	controllers.ImageBasedUpgrade.Idle	failed to cleanup backups	{"error": "failed to list Backup: failed to get API group resources: unable to retrieve the complete list of server APIs: velero.io/v1: the server could not find the requested resource"}
```
- before a cleanup LCA makes sure OADP is installed by checking for presence of OADP's CRDs
- improved checks when listing OADP resources

OCPBUGS-34520: add additional checks to validate if oadp is installed

---

api/seedreconfig/seedreconfig.go
controllers/prep_handlers.go
internal/clusterconfig/clusterconfig.go
internal/clusterconfig/clusterconfig_test.go
internal/common/consts.go
internal/recert/recert.go
lca-cli/ops/ops.go
lca-cli/postpivot/postpivot.go
lca-cli/seedclusterinfo/seedclusterinfo.go
lca-cli/seedcreator/seedcreator.go
utils/client_helper.go

Recert recently added ([1], [2]) some options that allow changing the
cluster's trust bundle (it's recommended you read the PRs for more
background about this).
The lifecycle-agent doesn't make use of the new options added to recert
Change the lifecycle-agent to use the new options added to recert
Multiple new fields have been added.
- `AdditionalTrustBundle` in `SeedReconfiguration`. This represents the
trust bundle to be used for seed-reconfiguration. This contains the
user-ca-bundle contents, the proxy configmap name, and the proxy configmap
contents.
- `AdditionalTrustBundle` in `SeedClusterInfo`. This represents the
state of the trust bundle in the seed cluster. This is simply booleans
indicating the presence or lack there-of of the user-ca-bundle and the
proxy configmap name (only …

Use the new recert additional trust bundle options

---

controllers/ibu_controller.go
controllers/seedgen_controller.go
internal/common/utils.go
lca-cli/cmd/ibuStaterootSetup.go
lca-cli/postpivot/postpivot.go
main/main.go
utils/client_middleware.go
utils/utils.go

This builds on https://github.com/openshift-kni/lifecycle-agent/pull/541.  We now have middleware that will do the retries, making all the client call implicitly retriable.
As long as clients are configured to include it during initialization...the middleware will intercept all calls and retry exponentially for max 3 mins if any of the error conditions are met.
/cc @donpenney

OCPBUGS-32493: make all client calls retriable with middleware

---

controllers/ibu_controller.go
controllers/prep_handlers.go
controllers/seedgen_controller.go
controllers/utils/conditions.go
internal/backuprestore/backup.go
internal/common/utils.go
lca-cli/postpivot/postpivot.go
main/main.go
utils/utils.go

This builds on https://github.com/openshift-kni/lifecycle-agent/pull/548 to clean up the existing explicitly wrapped client calls since they are redundant 
/cc @jc-rh  @Missxiaoguo

OCPBUGS-32493: remove redundant retry wrappers

---

utils/utils.go

Accidentally included the wrong error check during wrapped called cleanup.  (`client.IgnoreNotFound` should have been replaced with `k8serrors.IsNotFound` instead it was set to `k8serrors.IsAlreadyExists`)

OCPBUGS-32493: fix wrong error check

---

controllers/ibu_controller.go
controllers/prep_handlers.go
controllers/seedgen_controller.go
lca-cli/ops/mock_ops.go
lca-cli/ops/ops.go
lca-cli/seedclusterinfo/seedclusterinfo.go
lca-cli/seedcreator/seedcreator.go
main/main.go

This update adds checks to IBU and seedgen to ensure:
- container storage is setup shared, ie. is a mountpoint
- the mountpoint target for the seed image is the same as the mountpoint target on the running cluster
IBU requires container storage setup such that it is shared between stateroots. The configuration of the shared storage is up to the user, but the mountpoint target (eg. `/dev/disk/by-partlabel/varlibcontainers`) must be the same on both seed and target SNO.
If the seed image is generated on an SNO with a different container storage mountpoint target, the upgraded SNO may fail to boot, as the mountpoint target would not exist.
In order to prevent such a configuration mismatch, LCA has been updated to include checks for the container storage setup.
- If container storage is not …

OCPBUGS-34089: Add container storage mountpoint checks

---

utils/client_middleware.go

Retry middleware may detect and report watch calls (along with every explicit calls from lca) as WARNING if e.g api server is down. Generally this can be considered noise and if retry fails it will eventually be caught by the caller and reported possibly as an error anyway. 
Update the log to say DEBUG instead. 
/cc @donpenney

update logging msg for retry middleware

---

.ci-operator.yaml

Updating the base image for CI to be rhel9 so that the must gather works

OCPEDGE-1089: fix: use rhel9 for the CI build root

---

.ci-operator.yaml

Cherry-pick https://github.com/openshift-kni/lifecycle-agent/pull/590 to release-4.16

[release-4.16] OCPEDGE-1089: chore: use rhel9 for the CI build root

---

.ci-operator.yaml

Cherry-pick https://github.com/openshift-kni/lifecycle-agent/pull/590 to release-4.15

[release-4.15] OCPEDGE-1089: chore: use rhel9 for the CI build root

---

.ci-operator.yaml

Cherry-pick https://github.com/openshift-kni/lifecycle-agent/pull/590 to release-4.16

[release-4.14] OCPEDGE-1089: chore: use rhel9 for the CI build root

---

api/seedreconfig/seedreconfig.go
internal/clusterconfig/clusterconfig_test.go
internal/recert/recert.go
lca-cli/seedclusterinfo/seedclusterinfo.go
lca-cli/seedcreator/seedcreator.go
utils/client_helper.go
utils/crypto_dir.go

The ingress certificate's Subject.CN that LCA provides to recert, i.e. `ingress-operator.key`, along with the ingress CA private key of the target cluster, in order for HTTP clients to keep trusting the ingress certificate is incorrect, i.e. it is not contained in the ingress CA certificate. Recert regenerates the ingress CA certificate and its private key, instead of using the provided ingress private key of the target cluster. The latter leads in HTTP clients requesting an API resource via ingress using the cluster's CA certificates in their TLS transport to fail because they can't verify the ingress certificate.
After an IBU we should have the ingress CA certificates properly regenerated and signed by the provided target cluster's ingress private key, using the correct CN in the recert …

MGMT-19151: Fix ingress crt not signed by target ingress CA key

---

go.mod
go.sum
vendor/github.com/rh-ecosystem-edge/preinstall-utils/LICENSE
vendor/github.com/rh-ecosystem-edge/preinstall-utils/pkg/disk_ops.go
vendor/modules.txt

The purpose of this PR is to pick up a change to disk cleanup made in rh-ecosystem-edge/preinstall-utils@cf01558
This change is to ensure that in the case of thin provisioning we clean up all necessary disks in the correct order.
This has been tested in assisted-test infra with a 5 node cluster and an artificially created thin provisioning, the cluster installs correctly where it would not have done so before this change.
It was discovered that disk cleanup does not clean disks in every scenario.
When thin provisioned disk mappings are present, the existing installer is not able to clean them up. this is because the `_tdata` and `_tmeta` mappings are the only mappings that will be returned when filtering by associated disk.
The changed library code ensures that we search for a base DM and …

OCPBUGS-31570: Bump to latest preinstall utils for disk cleanup fixes

---

internal/prep/prep.go
lca-cli/ops/execute.go
lca-cli/ops/mock_ops.go
lca-cli/ops/ops.go

[MGMT-19505](https://issues.redhat.com//browse/MGMT-19505): IBU fails during lca-prep-stateroot-setup: failed to complete stateroot setup
In new version of crio was added a cleanup that if crio doesn't find image mount point it removes container.
When running with chroot and moint image , mount point is not created in the host namespace
and in this case crio removes the image at some point causing preparation logic to fail.
This change fixes the issue by using nsenter command for podman image mount.

MGMT-19505: IBU fails during lca-prep-stateroot-setup: failed to complete stateroot setup

---

controllers/seedgen_controller.go

On podman 5.3.1 and systemd 252-49 (OpenShift 4.19) the seed generation container, run with systemd-run via podman, while exiting with code 0 (successfully) it's stuck with status `stopped` instead of `exited`. This means that [conmon](https://github.com/containers/conmon), run as a separate process, did not cleanup after the container exited. 
In OCP 4.19 although seed generation completes successfully, the container `exited` status is never reached, leading to the SeedGenerator CR being stuck in a failed state. Podman 5.3 improved the container exit wait time. Since podman now exits a lot faster and systemd kills all processes of the unit's control group (e.g. conmon) right after the main process of the unit (i.e. podman) exits, conmon doesn't have a chance to cleanup after the …

OCPBUGS-49692: fix seedgen container being stuck as stopped

---

renovate.json

- Gomod updates are proving exceptionally noisey
- As Konflux is backported to more OCP versions it will only get worse
- Disable them for now, pending a re-evaluation later
- Also dependabot is already doing this in this repo anyway

Disable gomod updates from renovate.json

---

.tekton/build-pipeline.yaml
.tekton/lifecycle-agent-4-20-pull-request.yaml
.tekton/lifecycle-agent-4-20-push.yaml
.tekton/lifecycle-agent-operator-bundle-4-20-pull-request.yaml
.tekton/lifecycle-agent-operator-bundle-4-20-push.yaml

- The sast-coverity task often times out and is optional
- Until the task has been improved by the Konflux team we will skip it

Skip sast-coverity tekton task

---

.tekton/build-pipeline.yaml
.tekton/lifecycle-agent-4-19-pull-request.yaml
.tekton/lifecycle-agent-4-19-push.yaml
.tekton/lifecycle-agent-operator-bundle-4-19-pull-request.yaml
.tekton/lifecycle-agent-operator-bundle-4-19-push.yaml

Backport of two Konflux PRs (/cherry-pick does not work because the file names are different)
- https://github.com/openshift-kni/lifecycle-agent/pull/854
- https://github.com/openshift-kni/lifecycle-agent/pull/861

[release-4.19] Backport additional Konflux changes

---

.konflux/lock-runtime/redhat.repo
.konflux/lock-runtime/rpms.in.yaml
.konflux/lock-runtime/rpms.lock.yaml
.tekton/lifecycle-agent-4-20-pull-request.yaml
.tekton/lifecycle-agent-4-20-push.yaml
.tekton/lifecycle-agent-fbc-4-20-pull-request.yaml
.tekton/lifecycle-agent-fbc-4-20-push.yaml
.tekton/lifecycle-agent-operator-bundle-4-20-pull-request.yaml
.tekton/lifecycle-agent-operator-bundle-4-20-push.yaml
Dockerfile
Makefile

- Include arm64 as a build target in Konflux
- Update rpm lock configuration to include both architectures packages
- Update Dockerfile/Makefile to fix cross compiling to work both in and outside of Konflux

Enable multi-arch building for lifecycle-agent

---

api/seedreconfig/seedreconfig.go
internal/clusterconfig/clusterconfig.go
internal/clusterconfig/clusterconfig_test.go
internal/recert/recert.go
internal/recert/recert_test.go
lca-cli/postpivot/postpivot.go
lca-cli/postpivot/postpivot_test.go
lca-cli/seedclusterinfo/seedclusterinfo.go
lca-cli/seedclusterinfo/seedclusterinfo_test.go
utils/client_helper.go
utils/client_helper_test.go

Depend on rh-ecosystem-edge/recert#390
The lifecycle-agent is a core component responsible for managing Image-Based Upgrades (IBU) and Image-Based Install (IBI) operations in OpenShift Single Node OpenShift (SNO) clusters. It handles critical cluster lifecycle operations including:
* **Network Configuration Management**: Configuring node IPs, machine networks, cluster networks, and service networks during cluster transitions
* **Recertification (Recert)**: Re-signing certificates with updated cluster information (IPs, hostnames, etc.) when transforming seed images into target clusters
* **Post-Pivot Operations**: Managing network setup, DNS configuration, and kubelet configuration after cluster pivot operations
* **Seed Cluster Information**: Capturing and transforming network details …

MGMT-21201: Enable dual-stack clusters

---

go.mod
go.sum
vendor/github.com/golang/glog/glog.go
vendor/github.com/golang/glog/glog_file.go
vendor/github.com/golang/glog/glog_file_nonwindows.go
vendor/github.com/golang/glog/glog_file_windows.go
vendor/modules.txt

- Bumps  glog version from '1.2.1' to '1.2.4' to mitigate CVE-2024-45339

OCPBUGS-58604: Bump glog version to 1.2.4 to resolve CVE-2024-45339

---

.tekton/build-pipeline.yaml
.tekton/lifecycle-agent-4-20-pull-request.yaml
.tekton/lifecycle-agent-4-20-push.yaml
.tekton/lifecycle-agent-operator-bundle-4-20-pull-request.yaml
.tekton/lifecycle-agent-operator-bundle-4-20-push.yaml

For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Based on original changes from @rbean in our other operator repos
Assisted-by: Gemini

chore(KONFLUX-6210): fix and set name and cpe label for lifecycle-agent

---

.konflux/lock-runtime/rpms.in.yaml
.konflux/lock-runtime/rpms.lock.yaml

[CNF-19739](https://issues.redhat.com//browse/CNF-19739): Add missing EUS repos to rpm lock configuration
- This is required to receive updated packages for each 9.x release
- Re-run lock generation to update all packages

CNF-19739: Add missing EUS repos to rpm lock configuration
