- OWNERS
Extending reviewers/approvers to include larger team involved.
> Update owners with additional reviewers/approvers

- bundle/manifests/lifecycle-agent-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- bundle/manifests/lifecycle-agent-manager-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/manager/manager.yaml
Will revisit this after the first demo
> Use cluster-admin for running priviledged pod as root

- api/v1alpha1/types.go
- bundle/manifests/lifecycle-agent-manager-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- bundle/manifests/ran.openshift.io_imagebasedupgrades.yaml
- config/crd/bases/ran.openshift.io_imagebasedupgrades.yaml
Also update the bundle by running "make bundle"
> Add enum validation for stage

- controllers/ibu_controller.go
- controllers/ibu_controller_test.go
- Unit tests for `validateStageTransitions`
- Add `shouldTransition` and unit tests
- Fix bug when reconciling in PrepCompleted condition caused a
bad status
> Add unit test for stage transitions

- OWNERS
/cc @jc-rh @imiller0 @javipolo @leo8a
> Add reviewers to OWNERS

- README.md
- hack/lint.sh
- ibu-imager/Makefile
- ibu-imager/cmd/create.go
- ibu-imager/internal/ops/execute.go
- ibu-imager/internal/ops/ops.go
- ibu-imager/internal/ostreeclient/rpmostreeclient.go
- ibu-imager/internal/seed_creator/seed_creator.go
- ibu-imager/internal/seedcreator/seedcreator.go
- ibu-imager/internal/seedcreator/seedcreator_test.go
Follow up PR of the work done in #23.
> [imager] Enable golint and clean up warnings for Imager

- Makefile
- go.mod
- internal/clusterconfig/clusterconfig_test.go
- internal/clusterconfig/networkconfig.go
- internal/clusterconfig/networkconfig_test.go
- vendor/modules.txt
Adding ip validation for primary ip file if it will be changed in future
Adding internal folder to unitests
Adding new unitests
> Adding ip validation for primary ip file and new unitests

- ibu-imager/installation_configuration_files/scripts/installation-configuration.sh
- ibu-imager/installation_configuration_files/scripts/prepare-installation-configuration.sh
- ibu-imager/internal/seedcreator/seedcreator.go
Changing  configuration scripts to support single ip installation flow
> MGMT-16094: adding support for single ip installation process

- OWNERS
> Update OWNERS list

- ibu-imager/clusterinfo/clusterinfo.go
- ibu-imager/cmd/create.go
- ibu-imager/seedcreator/seedcreator.go
- internal/clusterconfig/clusterconfig.go
- internal/clusterconfig/clusterconfig_test.go
- utils/utils.go
Create cluster info object that will be provided to installation script in future.
Creating manifest.json on seed image that should be used in preparation phase
Adding additional cluster data for recert
> Create cluster info object that will be provided to installation script

- ibu-imager/cmd/create.go
- ibu-imager/hack/clean.sh
- ibu-imager/installation_configuration_files/conf/installation-configuration.env
- ibu-imager/installation_configuration_files/scripts/installation-configuration.sh
- ibu-imager/installation_configuration_files/services/installation-configuration.service
- ibu-imager/seedcreator/seedcreator.go
- internal/clusterconfig/clusterconfig.go
- internal/clusterconfig/clusterconfig_test.go
- utils/utils.go
Providing to recert new cluster name and domain
Adding dnsmasq custom.conf in order to support new domain.
> MGMT-15882: Cluster and domain renaming

- ibu-imager/installation_configuration_files/scripts/installation-configuration.sh
Added args to the recert command to allow the recert tool to update the /etc/mcs-machine-config-content.json file.
Also added --replace option to the podman run commands.
> Update recert cmd args

- Dockerfile
- HACKING.md
- ibu-imager/cmd/create.go
- ibu-imager/seedcreator/seedcreator.go
> ibu-imager: Fix new installation_configuration_files dir path

- ibu-imager/installation_configuration_files/scripts/installation-configuration.sh
- ibu-imager/installation_configuration_files/scripts/prepare-installation-configuration.sh
- ibu-imager/seedcreator/seedcreator.go
Moving to new dnsmasq configuration provided https://github.com/openshift/assisted-service/pull/5658/files#diff-5db168b848f6639a70b54fcd040b97dfeaf0ead692af19fc8154c48e0203831aR86
> Moving to new dnsmasq configuration

- ibu-imager/hack/clean.sh
- ibu-imager/installation_configuration_files/scripts/installation-configuration.sh
- ibu-imager/installation_configuration_files/scripts/prepare-installation-configuration.sh
- ibu-imager/seedcreator/seedcreator.go
Fixes for 4.14:
1. Removing node while creating seed image
2. Filtering multus and ovn certs from seed imag
> Fixes for 4.14

- HACKING.md
- Makefile
- controllers/ibu_controller.go
- controllers/idle_handlers.go
- controllers/prep_handlers.go
- controllers/utils/cmd.go
- ibu-imager/ostreeclient/rpmostreeclient.go
- undeploy and remove stateroot after a failed or successful Prep
> Add handle abort

- HACKING.md
- Makefile
- controllers/ibu_controller.go
- controllers/idle_handlers.go
- controllers/prep_handlers.go
- controllers/utils/cmd.go
- ibu-imager/ostreeclient/rpmostreeclient.go
> Revert "Add handle abort"

- Makefile
> Fix Makefile imager-unittest use of go-get-tool function

- HACKING.md
The section is added following failures trying the flow.
> Adding a prerequisites section.

- HACKING.md
- ibu-imager/common/consts.go
- ibu-imager/hack/clean.sh
- ibu-imager/seedcreator/seedcreator.go
> [Imager] Add common checks folder and fix nits in HACKING.md

- HACKING.md
- Makefile
- controllers/ibu_controller.go
- controllers/idle_handlers.go
- controllers/prep_handlers.go
- controllers/utils/cmd.go
- main/main.go
Undeploy and remove B side stateroot and clean up ibu files
> Add abort handler

- internal/clusterconfig/clusterconfig_test.go
- internal/clusterconfig/recert.go
> Fixing recert params for configuration file

- ibu-imager/cmd/create.go
- ibu-imager/seedcreator/seedcreator.go
> Cosmetic: avoid log `Printf/Println`, use `Info`

- .gitattributes
> `.gitattributes` wasn't properly marking generated files

- internal/bindata/prepSetupStateroot.sh
- internal/generated/zz_generated.bindata.go
> Fix problem with quoted kernel arguments

- internal/bindata/prepSetupStateroot.sh
- internal/generated/zz_generated.bindata.go
Remove additional single quoting from kernel args
/cc @tsorya 
/cc @donpenney
> Fix kernel arguments quoting

- Dockerfile
- controllers/idle_handlers.go
- controllers/prep_handlers.go
- controllers/upgrade_handlers.go
- internal/backuprestore/backup.go
- internal/backuprestore/common.go
- internal/common/utils.go
- internal/precache/helper.go
- internal/precache/precache.go
- internal/precache/precache_test.go
This PR consists of a minor refactoring of the plugins and controllers. Shared code is housed under `internal/common/utils.go`.
/cc @Missxiaoguo @pixelsoccupied
> Minor refactoring of plugins and common code

- controllers/prep_handlers.go
> Add check for nil precache status object

- ibu-imager/seedcreator/seedcreator.go
- utils/utils.go
> ibu-imager: Generic way to only RunOnce functions

- controllers/ibu_controller.go
- controllers/idle_handlers.go
- controllers/prep_handlers.go
- internal/precache/helper.go
- internal/precache/helper_test.go
- internal/precache/precache.go
- internal/precache/precache_test.go
- main/main.go
- main/precache-workload/main.go
Refactor pre-caching plugin to conform with Handler pattern used by the Backup&Restore and ExtraManifests plugins.
/cc @pixelsoccupied @jc-rh
> Minor refactoring of pre-caching plugin

- ibu-imager/seedcreator/seedcreator.go
- ibu-imager/seedrestoration/seedcleanup.go
- utils/utils.go
Follow up PR of #79, specifically addressing [this comment](https://github.com/openshift-kni/lifecycle-agent/pull/79#discussion_r1405396791).
> [imager] Cosmetic: Add HandleFilesWithCallback to utils and refactor

- .gitattributes
It wasn't capturing everything properly, making PR diffs very noisy
> Improve `.gitattributes`

- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/manifests/bases/lifecycle-agent.clusterserviceversion.yaml
required for midstream builds.
/cc @jc-rh @rauhersu @donpenney
> CNF-10483: Upgrade graph configuration in LCA bundle

- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/default/manager_auth_proxy_patch.yaml
> Disable http2 on the rbac proxy

- controllers/ibu_controller.go
- controllers/idle_handlers.go
- controllers/prep_handlers.go
- controllers/upgrade_handlers.go
- ibu-imager/ostreeclient/mock_rpmostreeclient.go
- ibu-imager/ostreeclient/rpmostreeclient.go
systemctl reboot after the pre pivot steps.
> Pivot to new stateroot

- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/seedgen_controller.go
Added a system validation check to ensure the config of the SNO is appropriate for generating a seed image. Currently, this checks:
- Are any ACM addon namespaces present (ie. observability must not be enabled on seed SNO)
- Is the required dnsmasq config present, to support the cluster changes post-upgrade?
> CNF-10554: seedgen: Add system validation check

- ibu-imager/ops/ops.go
- ibu-imager/seedcreator/seedcreator.go
[MGMT-16344](https://issues.redhat.com//browse/MGMT-16344): waiting for ovn to exit after node deletion and before stopping all containers
Stopping  recert etcd container gracefully
> MGMT-16344: waiting for ovn to exit after node deletion and before stopping all containers

- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/upgrade_handlers.go
- internal/common/utils.go
- internal/healthcheck/healthcheck.go
Poll in parallel to see if ClusterOperators + MachineConfigPool + ClusterServiceVersion are all ready
> health check

- controllers/upgrade_handlers.go
Status decision is made inside of pre-pivot and post-pivot functions. The caller should simply return what it receives from these functions.
> Fix reconciliation for upgrade

- docs/backuprestore-with-oadp.md
/cc @browsell @donpenney @pixelsoccupied
> Create doc for using backup and restore

- controllers/prep_handlers.go
- ibu-imager/installation_configuration_files/scripts/prepare-installation-configuration.sh
- ibu-imager/postpivot/postpivot.go
- ibu-imager/seedcreator/seedcreator.go
- ibu-imager/seedrestoration/seedcleanup.go
- internal/clusterconfig/clusterconfig.go
- internal/clusterconfig/clusterconfig_test.go
- internal/common/consts.go
- utils/utils.go
1. Moving seed manifest.json to /var/seed_data in order to allow reeding seed info manifest in IBI process
2. Delete ovn certs folders as part of seed creation and not just filter
them from tar
3. Set hostname by writing value from hostname var in cluster info and
not copying etc/hostname file
4. Move cluster id change to post pivot
> Changes required for IBI 

- ibu-imager/seedrestoration/seedcleanup.go
Adds a conditional cleanup to avoid the execution of certain cleanup steps that could cause issues.
/cc @tsorya @donpenney
> MGMT-16334: [Imager] Add selective cleanup based on successful stages

- api/v1alpha1/types.go
- bundle/manifests/lca.openshift.io_imagebasedupgrades.yaml
- config/crd/bases/lca.openshift.io_imagebasedupgrades.yaml
- controllers/utils/conditions.go
- Add State column that shows the type of last condition whose status has been changed
- Add Details column that shows the message of last condition whose status has been changed
SetStatusCondition tries to keep the conditions sorted by the time their status was last changed
> Add printer columns for ibu

- internal/healthcheck/healthcheck_test.go
/cc @donpenney 
/cc @Missxiaoguo 
/cc @jc-rh
> health check unit tests

- HACKING.md
Updated the documented method for setting PRECACHE_BEST_EFFORT=TRUE in HACKING.md to use the "oc set env" command.
> Update HACKING.md command for setting PRECACHE_BEST_EFFORT

- controllers/seedgen_controller.go
When the imager is launched through the `SeedGenerator` CR, we want the
to have the option to skip the recert stage of the seed image generation.
To that end this commit adds a new environment variable
`SEEDGEN_IMAGER_SKIP_RECERT` which when set to the value `TRUE`, will
make the `SeedGeneratorReconciler` ask the imager to skip recert
validation
This is useful when recert fails but we still want an image to be
created so that it can be shared for debugging and troubleshooting
purposes
> `SEEDGEN_IMAGER_SKIP_RECERT` to skip recert validation

- bundle/manifests/lifecycle-agent-manager-config_v1_configmap.yaml
- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/manager/controller_manager_config.yaml
- config/manager/manager.yaml
> Use Recreate strategy for LCA Deployment and drop leader election

- Dockerfile
- controllers/prep_handlers.go
- ibu-imager/cmd/ibi.go
- ibu-imager/ibi-preparation/ibipreparation.go
- ibu-imager/ops/execute.go
- ibu-imager/ops/mock_execute.go
- internal/common/utils.go
- internal/ostreeclient/mock_ostreeclient.go
- internal/ostreeclient/ostreeclient.go
- internal/precache/workload/pullImages.go
- internal/prep/prep.go
- main/main.go
- main/precache-workload/main.go
IBI FLOW: Adding new command to lca that will run IBI installation flow
Run state root preparation flow on iso
Precache images
> MGMT-16479: Adding new command to lca that will run IBI installation flow

- internal/prep/prep.go
- internal/prep/prep_test.go
Many functions in the prep code were unnecessarily exported
> Cosmetic - prep unexport functions

- controllers/seedgen_controller.go
- ibu-imager/seedcreator/seedcreator.go
- internal/prep/prep.go
- utils/client_helper.go
- utils/utils.go
> restrict permissions on files generated by LCA for IBU

- controllers/idle_handlers.go
- internal/backuprestore/common.go
- internal/backuprestore/mocks/mock_backuprestore.go
> dont delete oadp operator in idle cleanup

- api/seedreconfig/seedreconfig.go
- internal/clusterconfig/clusterconfig.go
- internal/clusterconfig/clusterconfig_test.go
- lca-cli/postpivot/postpivot.go
- utils/utils.go
Still in process
[MGMT-16154](https://issues.redhat.com//browse/MGMT-16154): Configure provided ssh key
Create early access ssh key file
Create override ssh key machine configs
> MGMT-16154: Configure provided ssh key

- docs/image-based-upgrade.md
Co-authored by: Jun Chen <jun@redhat.com
> Add IBU doc.

- docs/backuprestore-with-oadp.md
/cc @browsell @donpenney @sakhoury
> Update backup restore doc

- internal/clusterconfig/clusterconfig_test.go
A lot of repetition made adding new test cases confusing
> `clusterconfig_test.go` refactor

- lca-cli/ops/ops.go
Remove seed image even if it is not mounted as part of `UnmountAndRemoveImage`
> CNF-11184: remove seed image even if it is not mounted

- internal/recert/recert.go
- lca-cli/postpivot/postpivot.go
Reverting https://github.com/openshift-kni/lifecycle-agent/pull/280 and https://github.com/openshift-kni/lifecycle-agent/pull/284 due to IBU failures with recovery of etcd post-upgrade
> Revert prs

- ib-cli/README.md
- ib-cli/installationiso/installationiso.go
- utils/utils.go
The binary failed when executed outside of lifecycle-agent repo Updated readme as well
> Fix ib-cli butane template rendering

- lca-cli/seedcreator/seedcreator.go
This change leaves the seed node object intact in the seed image, as [recert is going to delete it](https://github.com/rh-ecosystem-edge/recert/blob/v0/src/ocp_postprocess.rs#L399) as part of its OCP post-process flow. 
This resolves an etcd rollout, which is triggered due to the `etcd-all-certs` secret that is [emptied](https://github.com/openshift/cluster-etcd-operator/blob/551193bb82d1310bf75b04bd9727a18ad61051fc/pkg/operator/etcdcertsigner/etcdcertsignercontroller.go#L178-L217) by the cluster etcd operator when the node is deleted via the k8s API. Since his secret is empty in the seed image, recert cannot adjust it on the target SNO and thus make the cluster etcd operator happy, so a new etcd rollout is triggered. 
By deleting the node object via recert and not via the k8s API, once …
> MGMT-16780: remove node deletion from seed image creation

- internal/recert/recert.go
- lca-cli/postpivot/postpivot.go
Reverts openshift-kni/lifecycle-agent#299
Following https://github.com/rh-ecosystem-edge/recert/pull/96
> Revert "Revert prs"

- docs/image-based-upgrade.md
> Update IBU Doc

- controllers/prep_handlers.go
- controllers/prep_handlers_test.go
- go.mod
Seed OCP version must be greater than the target OCP for prep to complete
> CNF-11135: validate seed OCP version

- controllers/seedgen_controller.go
The pull-secret sanitization function waits until the file has been updated by the MCO. This update also adds a call to the MCP health check to ensure MCO has completed handling the rendered machine-config before continuing with seed generation.
> OCPBUGS-29892: seedgen: Add MCP health check to pull-secret sanitization

- HACKING.md
- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/ibu_controller.go
- controllers/seedgen_controller.go
- docs/seed-image-generation.md
Manual cherry-pick of https://github.com/openshift-kni/lifecycle-agent/pull/351
/cc @browsell
> [release-4.15] CNF-11452: seedgen: Remove hubKubeconfig and hub interaction

- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/rbac/role.yaml
- go.mod
- internal/clusterconfig/clusterconfig.go
- internal/clusterconfig/clusterconfig_test.go
Reverts openshift-kni/lifecycle-agent#375
> Revert "MGMT-17115: Save the custom catalog sources as extra manifests"

- .snyk
/cc @jc-rh 
This should unblock https://github.com/openshift/release/pull/49688
> CNF-11561: snyk secure ignore vendor

- api/seedgenerator/v1alpha1/types.go
- bundle/manifests/lca.openshift.io_seedgenerators.yaml
- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/crd/bases/lca.openshift.io_seedgenerators.yaml
- config/manifests/bases/lifecycle-agent.clusterserviceversion.yaml
> OCPBUGS-30317: seedgen: add description to seedgen.spec fields

- api/v1alpha1/types.go
- bundle/manifests/lca.openshift.io_imagebasedupgrades.yaml
- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/crd/bases/lca.openshift.io_imagebasedupgrades.yaml
- config/manifests/bases/lifecycle-agent.clusterserviceversion.yaml
/cc @donpenney @jc-rh @browsell @Missxiaoguo
> OCPBUGS-30316: Add description to several IBU spec fields

- api/v1alpha1/types.go
- bundle/manifests/lca.openshift.io_imagebasedupgrades.yaml
- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/crd/bases/lca.openshift.io_imagebasedupgrades.yaml
- config/manifests/bases/lifecycle-agent.clusterserviceversion.yaml
This is a manual cherry-pick of https://github.com/openshift-kni/lifecycle-agent/pull/389
/cc @browsell
> [release-4.15] OCPBUGS-30316: Add description to several IBU spec fields

- api/v1alpha1/types.go
- bundle/manifests/lca.openshift.io_imagebasedupgrades.yaml
- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/crd/bases/lca.openshift.io_imagebasedupgrades.yaml
- config/manifests/bases/lifecycle-agent.clusterserviceversion.yaml
> (cosmetic) Enhance ExtraManifests description in IBU spec

- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/rbac/role.yaml
- docs/backuprestore-with-oadp.md
- docs/image-based-upgrade.md
- internal/clusterconfig/clusterconfig.go
- internal/clusterconfig/lvmconfig.go
- internal/clusterconfig/lvmconfig_test.go
- internal/extramanifest/extramanifest.go
- lca-cli/postpivot/postpivot.go
- lca-cli/postpivot/postpivot_test.go
- main/main.go
- utils/utils.go
- Move localvolume restore to postpivot service
- Refactor postpivot service to use func from extramanifest plugin to apply manifests
/cc @browsell @donpenney
> CNF-11550: Move localvolume restore to postpivot service

- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/idle_handlers.go
- controllers/prep_handlers.go
- controllers/upgrade_handlers.go
- controllers/upgrade_handlers_test.go
- internal/healthcheck/healthcheck.go
- internal/healthcheck/healthcheck_test.go
- must-gather/collection-scripts/gather_lca
- enable health checks for before prep, prepivot and finalize (Idle) starts 
- Validate CertificateSigningRequest health
> CNF-11531: enable health checks for prep, prepivot and finalize (Idle) + hc for CSRs

- ib-cli/installationiso/data/install-rhcos-and-restore-seed.sh
> MGMT-17283 - IBI - Run restorecon after mounting /var/lib/containers

- Dockerfile
/cc @rauhersu 
/cc @jc-rh 
/assign @rauhersu
> CNF-11274: required dockerfile updates for midstream

- ib-cli/installationiso/data/install-rhcos-and-restore-seed.sh
With this we should be more generic on detecting the partition block devices, and so allow disks with paths like
/dev/disk/by-id/whatever
/dev/nvme0n1
> IBI: Detect partition filepaths and use partition labels when possible

- docs/backuprestore-with-oadp.md
- docs/image-based-upgrade.md
> CNF-11188: docs update for disable-auto-import annotation

- HACKING.md
- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/manager/manager.yaml
- internal/precache/helper.go
- must-gather/collection-scripts/gather_lca
> OCPBUGS-32360: fix all "lifecyle" spelling errors

- api/v1alpha1/types.go
- api/v1alpha1/zz_generated.deepcopy.go
- bundle/manifests/lca.openshift.io_imagebasedupgrades.yaml
- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/crd/bases/lca.openshift.io_imagebasedupgrades.yaml
- config/manifests/bases/lifecycle-agent.clusterserviceversion.yaml
- config/samples/lca_v1alpha1_imagebasedupgrade.yaml
- docs/examples.md
/cc @browsell @donpenney @jc-rh
> OCPBUGS-32336: [IBU] Remove AdditionalImages from IBU CRD

- controllers/seedgen_controller.go
> OCPBUGS-32244: remove kubeadmin secret check from seedgen validation

- internal/clusterconfig/clusterconfig_test.go
- lca-cli/postpivot/postpivot.go
- lca-cli/postpivot/postpivot_test.go
- lca-cli/seedclusterinfo/seedclusterinfo.go
- utils/client_helper.go
This reverts commit 4ea5d9ec458e27175d107aa2c647c59c519b2d4d.
Reverting cause of rbac issue, will reopen with the fix
> Revert "MGMT-16807: set correct no proxy and proxyStatus"

- HACKING.md
Re-organized the rollback `HACKING.md` disabling docs to remove the split between "error" rollbacks and the "init monitor" rollback. I found the split unnecessary, as I wish I had a simple snippet with all three annotations that I could just copy to disable rollback altogether. Also the original docs mentioned the same annotation twice, so that was a bit confusing.
[PREVIEW](https://github.com/omertuc/lifecycle-agent/blob/rollbackdoc/HACKING.md#automatic-rollback-on-failure)
> Rephrasing of the rollback `HACKING.md` docs

- Dockerfile
- internal/precache/helper.go
- internal/precache/helper_test.go
- lca-cli/cmd/ibuPrecacheWorkload.go
A simple move from ./main to ./lca-cli to build precache in one shot 
/cc @donpenney @rauhersu @jc-rh
> CNF-12605: move precache workload cli into lca-cli

- api/ibiconfig/ibiconfig.go
- ib-cli/cmd/createiso.go
- ib-cli/installationiso/data/ibi-butane.template
- ib-cli/installationiso/data/install-rhcos-and-restore-seed.sh
- ib-cli/installationiso/installationiso.go
- ib-cli/installationiso/installationiso_test.go
- lca-cli/cmd/ibi.go
- lca-cli/cmd/ibuStaterootSetup.go
- lca-cli/ibi-preparation/ibipreparation.go
- lca-cli/ibi-preparation/ibipreparation_test.go
- lca-cli/ops/mock_ops.go
- lca-cli/ops/ops.go
- utils/ibi_config.go
MGMT-17801: Change lca-cli cmd flags into configuration file
1. Adding configuration file for lca-cli command
2. Changing iso builder to create configuration file for lca-cli
> MGMT-17801: Change lca-cli cmd flags into configuration file

- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/rbac/role.yaml
- internal/clusterconfig/clusterconfig.go
- internal/clusterconfig/clusterconfig_test.go
- lca-cli/postpivot/postpivot.go
- lca-cli/postpivot/postpivot_test.go
- lca-cli/seedclusterinfo/seedclusterinfo.go
- utils/client_helper.go
We should create NoProxy and proxyStatus exactly same way as cluster network operator. Took CNO function and made it match lca. Added service and cluster networks to seedInfo
> MGMT-16807: set correct no proxy and proxyStatus

- controllers/ibu_controller.go
- controllers/ibu_controller_test.go
- controllers/idle_handlers.go
- controllers/idle_handlers_test.go
- controllers/prep_handlers.go
- controllers/rollback_handlers.go
- controllers/seedgen_controller.go
- controllers/upgrade_handlers.go
- controllers/upgrade_handlers_test.go
- controllers/utils/conditions.go
- internal/backuprestore/backup.go
- internal/backuprestore/backup_test.go
- internal/backuprestore/common.go
- internal/backuprestore/restore.go
- internal/common/utils.go
- internal/extramanifest/extramanifest.go
- internal/extramanifest/extramanifest_test.go
- internal/precache/helper.go
- internal/precache/helper_test.go
- internal/precache/precache.go
- internal/precache/precache_test.go
- internal/prep/prep_stateroot_setup_job.go
- internal/reboot/reboot.go
- internal/reboot/reboot_test.go
- lca-cli/cmd/create.go
- lca-cli/cmd/ibuStaterootSetup.go
- main/main.go
- utils/utils.go
Accidental api version replacement in `internal/backuprestore/common.go` from #497 
Restored the accidental replacement
Replaced all `lcav1` imports with `ibuv1`, to be consistent with `seedgenv1`
> Fix api version replacement

- Dockerfile
- Makefile
- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/lifecycle-agent.clusterserviceversion.yaml
> Upversion main to 4.17

- Dockerfile
- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/default/manager_auth_proxy_patch.yaml
> Lock cli and rbac proxy image version for 4.16

- internal/common/consts.go
We recently upversioned the api from v1alpha1 to v1
The LCA on pre and post pivot must be running the same api version for the IBU save/restore to work.
SeedFormatVersion incremented
> Update seed format version due to the api version change

- lca-cli/ops/ops.go
When reconfiguring a seed image, we have to perform a lot of etcd delete operations. This leaves etcd is a fragmented state, which could possibly harm its performance when its later actually used for OCP and thus lengthen the IBX duration.
Running defrag command allows us to minimize defrag state in etcd db as example 
Without running defrag on seed i got 68% if difference between db size and size in use
`[root@seed core]# oc exec etcd-seed -c etcd -n openshift-etcd -- etcdctl endpoint status --cluster -w json | jq '.[].Status|"dbSize: " + (.dbSize|tostring) + ", dbSizeInUse: " + (.dbSizeInUse|tostring) + ", (dbSize-dbSizeInUse)/dbSize => " + ((.dbSize - .dbSizeInUse)/.dbSize*100|tostring)+"%"'
"dbSize: 107253760, dbSizeInUse: 33562624, (dbSize-dbSizeInUse)/dbSize => 68.70727515753295%"
` …
> MGMT-17652: Possibly improve etcd performance through defrag/compaction

- internal/clusterconfig/clusterconfig.go
- utils/client_helper.go
[MGMT-16515](https://issues.redhat.com//browse/MGMT-16515): in order to set machine network in node ip hint file in post pivot we should take it from target
[MGMT-16515](https://issues.redhat.com//browse/MGMT-16515): in order to set machine network in node ip hint file in post pivot we should take it from target
This pr adds logic to take machine network from install-config of upgraded sno and set it in seed reconfiguration api.
Post pivot will use this field and set it in nodeip hint file in order require from node-configuration service to set kubelet ip from the machine network we provided
> MGMT-16515: in order to set machine network in node ip hint file in post pivot we should take it from target

- docs/backuprestore-with-oadp.md
Cleanup and restructure backup and restore upstream doc to make it easier to follow
/cc @leo8a
> backup restore doc update

- api/ibiconfig/ibiconfig.go
- ib-cli/cmd/createiso.go
- ib-cli/installationiso/data/ibi-butane.template
- ib-cli/installationiso/installationiso.go
- ib-cli/installationiso/installationiso_test.go
[MGMT-17949](https://issues.redhat.com//browse/MGMT-17949): Proxy params for installation iso
Setting proxy setting as part of installation service in installation iso
As part of installation flow on installation iso we need to pull seed image and precache seed images.  We need to add proxy settings to installation service in order for it to work 
Set proxy params as part of installation service in installation iso
> MGMT-17949: Proxy params for installation iso

- api/ibiconfig/ibiconfig.go
- ib-cli/cmd/createiso.go
- ib-cli/installationiso/data/ibi-butane.template
- ib-cli/installationiso/installationiso.go
- ib-cli/installationiso/installationiso_test.go
[MGMT-17011](https://issues.redhat.com//browse/MGMT-17011): Allow providing additional trusted bundle to installation iso.
In order to install ibi with proxy and mirror registry we should be able to provide additional trusted bundle for installation iso. 
Provided additional trusted bundle file is read and added to installation ignition to pki/anchors same way as assisted installer is doing it in discovery ignition
> MGMT-17011: Allow providing additional trusted bundle to installation iso.

- controllers/upgrade_handlers.go
NO-ISSUE: in case there is no oadp content we should not try to bring it.
If user didn't propvide oadp content in upgrade cr we should not try to bring
Skip oadp content gathering in case it was not asked
> NO-ISSUE: in case there is no oadp content we should not try to bring it

- api/ibiconfig/ibiconfig.go
- ib-cli/cmd/createiso.go
- ib-cli/installationiso/data/ibi-butane.template
- ib-cli/installationiso/installationiso.go
- ib-cli/installationiso/installationiso_test.go
[MGMT-16859](https://issues.redhat.com//browse/MGMT-16859): Provide an option to configure mirror registry in installation iso
We need to be able to pull images in installation iso, in case of mirror registry we must configure registry.conf file in order to be able to pull those images
Add mirror-registry cli param for ib-cli in order to get path to mirror registry config file
> MGMT-16859: Provide an option to configure mirror registry in installation iso

- lca-cli/postpivot/postpivot.go
- lca-cli/postpivot/postpivot_test.go
NO-ISSUE: In order to handle case for static ip configuration and without provided nodeip (IBI flow) we need to restart newtork manager before running nodeip configuration service.
> NO-ISSUE: handle case for static ip configuration without provide node ip (IBI) 

- controllers/prep_handlers.go
LCA uses labels on the seed image for certain config information, which allows validation against the seed image to ensure it is compatible.
The image labels can be inspected prior to pulling the seed image, in order to do validation prior to the pull. Since the seed image is more than 1G, doing this ahead of the pull can save downloading the image in the case where the validation would fail.
Using `skopeo inspect` to remotely access the image labels, rather than `podman inspect`, we can validate the seed image using the labels before pulling the image.
> CNF-12806: IBU: Inspect seed image before pulling

- lca-cli/seedcreator/seedcreator.go
During seed generation, a list of all images on the seed SNO is collected, for use in precaching. For some operators, however, this may not be a complete list of required images, as images may be pulled at runtime based on configuration that may not be present on the seed SNO. This will result on such images being pulled post-pivot.
In addition to the images present on the seed SNO, this update extends seedgen to also scan the installed CSVs to include relatedImages from the CSV specs in the image list. This ensures that those missing images are included during precaching.
> OCPBUGS-35078: Add CSV relatedImages to seed containers.list

- api/ibiconfig/ibiconfig.go
- ib-cli/README.md
- ib-cli/cmd/createiso.go
> NO-ISSUE: update ib-cli documentation

- lca-cli/postpivot/postpivot.go
- lca-cli/postpivot/postpivot_test.go
NO-ISSUE: in case node ip  was not provided, dnsmasq condifuration should run after setting node ip
If node ip was not provided as part of IBI flow we run node-ip configuration service that should set node ip and only after that we should run dnsmasq configuration
> NO-ISSUE: in case node ip  was not provided, dnsmasq condifuration should run after setting node ip

- docs/image-based-upgrade.md
Missing double quote on upgrade md.
Missing double quote on upgrade md.
> missing quotes on image-based-upgrade.md

- api/ibiconfig/ibiconfig.go
> NO-ISSUE: ibi config api comments updates

- docs/image-based-upgrade.md
If the seed image is stored in a private registry that is not covered by the cluster's common pull secrets, a separate pull secret must be created in the openshift-lifecycle-agent namespace and referenced by the IBU CR in order for the Prep stage to access the image. This update adds an example pull-secret to the IBU doc as an aid to the user.
> docs: Add pull-secret example to IBU doc

- ib-cli/README.md
- ib-cli/installationiso/installationiso.go
- ib-cli/installationiso/installationiso_test.go
- internal/common/consts.go
- lca-cli/ibi-preparation/ibipreparation.go
- lca-cli/ibi-preparation/ibipreparation_test.go
[MGMT-16608](https://issues.redhat.com//browse/MGMT-16608): Support post deployment tasks
As part of ibi installation we want to support post deployment script option.
Adding logic were user drops post.sh file with bash code in working folder, we will add it to installation ignition and run.
> MGMT-16608: Support post deployment tasks

- docs/seed-image-generation.md
Seed generation doc has been updated to expand the pre-requisites section with additional information about seed SNO criteria and alignment with target SNOs.
> docs: Update seedgen prereqs section

- Dockerfile
- Makefile
- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/lifecycle-agent.clusterserviceversion.yaml
> Upversion to 4.18

- internal/backuprestore/backup_test.go
Fix the race condition in the testcase for CleanupBackups. To mock the deletion of a backup, backup CR should be deleted first, followed by the backupDeleteRequest CR.
> NO-ISSUE: Fix unittest for CleanupBackups

- Dockerfile
- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/default/manager_auth_proxy_patch.yaml
> [release-4.17] Pin version of origin-cli-artifacts and kube-rbac-proxy

- lca-cli/postpivot/postpivot.go
[MGMT-18910](https://issues.redhat.com//browse/MGMT-18910): Run once  apply static network in order not to fail in case installation service was restarted
In case of restart or failure of installation service we will try to reapply static network configuration though it was successfully applied already and it causes failure even though we can succeed on second run
> MGMT-18910: Run once  apply static network in order not to fail in case installation service was restarted

- lca-cli/seedcreator/seedcreator.go
[MGMT-18928](https://issues.redhat.com//browse/MGMT-18928): take first image from .repoDigests
While precaching images we pull all the images in parallel,
some of them are pulled twice cause they have more than one repoDigest, though it is totally same image.
Pulling them in parallel can cause podman to corrupt it though it finish ok
> MGMT-18928: take first image from .repoDigests

- lca-cli/seedcreator/seedcreator.go
This reverts commit 279f0c6a5514a796bceb5d8a7b5565ca16764459.
failed to reproduce issue locally, no need to change the logic if we can't reproduce it anymore
> Revert "MGMT-18928: take first image from .repoDigests"

- api/seedreconfig/seedreconfig.go
- internal/clusterconfig/clusterconfig.go
- internal/clusterconfig/clusterconfig_test.go
- lca-cli/postpivot/postpivot.go
- lca-cli/postpivot/postpivot_test.go
- utils/client_helper.go
- utils/utils_test.go
User can add node labels and don't want to loose them after upgrade, this pr will save target node labels and they will be reapplied on post pivot.
In order not to reapply default labels we are filtering them from the list
https://issues.redhat.com/browse/OCPBUGS-42966
> OCPBUGS-42966: Readding node labels from target on post pivot

- api/ibiconfig/ibiconfig.go
- lca-cli/ibi-preparation/ibipreparation.go
- lca-cli/ibi-preparation/ibipreparation_test.go
[MGMT-19191](https://issues.redhat.com//browse/MGMT-19191): Provide a way to add coreos installer params for installation phase
Adding new field CoreosInstallerParams to image based install command to customize coreos installer command in lca cli
> MGMT-19191: Provide a way to add coreos installer params for installation phase

- lca-cli/ibi-preparation/ibipreparation.go
- lca-cli/ibi-preparation/ibipreparation_test.go
[MGMT-19168](https://issues.redhat.com//browse/MGMT-19168): Cleanup original stateroot after IBI install
> MGMT-19168: Cleanup original stateroot after IBI install

- Makefile
- bundle/manifests/lca.openshift.io_imagebasedupgrades.yaml
- bundle/manifests/lca.openshift.io_seedgenerators.yaml
- config/crd/bases/lca.openshift.io_imagebasedupgrades.yaml
- config/crd/bases/lca.openshift.io_seedgenerators.yaml
https://redhat.enterprise.slack.com/archives/C05JHD9QYTC/p1731510290954959?thread_ts=1731510290.954959&cid=C05JHD9QYTC
> Upversion controller-gen to v0.14.0

- Makefile
- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/default/manager_auth_proxy_patch.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/lifecycle-agent.clusterserviceversion.yaml
> Upversion to 4.19

- controllers/seedgen_controller.go
Rarely when cleaning ACM CRDs, an `AppliedManifestWork` remains and causes seedgen to timeout. This commit deletes the CRDs before namespaces in order to prevent this issue.
The controller responsible for handling the finalizer on `AppliedManifestWork` is removed when deleting ACM namespaces. If for some reason any `AppliedManifestWork` or similar object remains (they should have been deleted when namespaces were deleted) it will get stuck on `Terminating` because there is no pod to handle the finalizer.
This seems like a bug in ACM manifestwork. But we can work around it by deleting the CRDs first before deleting namespaces.
> OCPBUGS-44851: Delete ACM CRDs before ACM namespaces in SeedGen cleanup

- internal/clusterconfig/clusterconfig.go
LCA saves the idms/icsp CRs on the target cluster prior to booting to the new version and restoring them
Currently we save the spec section only. Need to include the labels and annotations from the object meta.
> OCPBUGS-50704: Include labels/annotations when saving idms/icsp

- .tekton/OWNERS
- OWNERS
> Update tekton OWNERS

- .ci-operator.yaml
- Dockerfile
- controllers/seedgen_controller.go
- go.mod
- hack/golangci-lint.sh
- internal/extramanifest/extramanifest.go
- internal/healthcheck/healthcheck.go
- internal/imagemgmt/imagemgmt.go
- internal/precache/helper.go
- lca-cli/cmd/ibuStaterootSetup.go
- lca-cli/ops/ops.go
- lca-cli/postpivot/postpivot.go
Some project alignment is necessary alongside Konflux onboarding
https://issues.redhat.com/browse/CNF-15329
- Update project to golang 1.23.0
- Prep Dockerfile for Konflux build
- Update golangci-lint to a version compatible with golang 1.23
- Ignore new warnings exposed by linter update as they are out of scope for this
These changes are necessary to support Konflux onboarding: https://github.com/openshift-kni/lifecycle-agent/pull/763
n/a
> Pre-Konflux Alignment for LCA Repo

- OWNERS
- OWNERS_ALIASES
- Groups need to be defined as an alias to work correctly
> Fix OWNERS configuration

- .tekton/lifecycle-agent-4-19-push.yaml
- .tekton/lifecycle-agent-operator-bundle-4-19-pull-request.yaml
- .tekton/lifecycle-agent-operator-bundle-4-19-push.yaml
- konflux_clusterserviceversion_overlay.data
- Now that Konflux has built both images I can add the digests here
> CNF-15329: Update digest images for csv overlay

- konflux_clusterserviceversion_overlay.data
- konflux_clusterserviceversion_overlay.sh
- renovate.json
- Fix renovate.json configuration
- Allow spaces and comments in csv overlay file
- Add spaces to csv overlay to prevent merge conflicts
> CNF-15329: Port last round of Konflux fixes from TALM

- Dockerfile
- Makefile
- hack/bashate.sh
- hack/generate-dnsmasq-site-policy-section.sh
- hack/shellcheck.sh
- I got a new computer (ARM macbook) and needed to test out some compiling things, so figured I may as well do something useful while I'm testing
- LCA has several hard coded x86_64 instances that cause issues when attempting to cross compile
- Allow compiling arm64 from amd64 and vice-versa
- I have been able to compile both directions with this change using containerized RHEL environments
- The Makefile and Dockerfile required the largest changes as passing the architecture in is required in both
- I also hit a minor issue with the shellcheck script which was also easy to fix
> CNF-17268: Configure cross compiling for LCA

- .tekton/lifecycle-agent-4-19-pull-request.yaml
- .tekton/lifecycle-agent-4-19-push.yaml
- .tekton/lifecycle-agent-operator-bundle-4-19-pull-request.yaml
- .tekton/lifecycle-agent-operator-bundle-4-19-push.yaml
- Update the branch Konflux is checking against
> [release-4.19] Update Konflux target branch to release-4.19

- Makefile
- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/manager/kustomization.yaml
- config/manifests/bases/lifecycle-agent.clusterserviceversion.yaml
> Upversion to 4.20

- .tekton/lifecycle-agent-operator-bundle-4-19-push.yaml
- bundle.konflux.Dockerfile
- konflux_build_args.conf
- renovate.json
[CNF-15329](https://issues.redhat.com//browse/CNF-15329): Port final fixes from TALM
- Update renovate.json configuration
- Update formatting for konflux_build_args to prevent errorenous merge conflicts
> CNF-15329: Port final fixes from TALM

- .tekton/build-pipeline.yaml
- renovate.json
- Include commit from Konflux bot
- Account for new mandatory parameters
- Update to latest task versions for good measure
> Update Konflux References

- .tekton/lifecycle-agent-4-20-pull-request.yaml
- .tekton/lifecycle-agent-4-20-push.yaml
- .tekton/lifecycle-agent-operator-bundle-4-20-pull-request.yaml
- .tekton/lifecycle-agent-operator-bundle-4-20-push.yaml
We only want to run the Konflux pipelines when it is appropriate to do so
If they run all the time they will waste time and resources
Limit the Konflux builds to running based on what files were changed
By inspecting the Dockerfile I have identified most of the areas where a code change would impact the container build. I have also included some additional codegen/config directories.
> Update `on-cel-expression` values for tekton pipelines to limit unnecessary builds

- .konflux/bundle.konflux.Dockerfile
- .konflux/konflux_build_args.conf
- Forgot to include this earlier
> [release-4.19] Fix build argument formatting in 4.19

- .tekton/lifecycle-agent-4-19-pull-request.yaml
- .tekton/lifecycle-agent-4-19-push.yaml
- .tekton/lifecycle-agent-operator-bundle-4-19-pull-request.yaml
- .tekton/lifecycle-agent-operator-bundle-4-19-push.yaml
- Could not use automated cherry pick as the file names changed on up-version to 4.20
> [release-4.19] Update `on-cel-expression` values for tekton pipelines to limit unnecessary builds

- .tekton/build-pipeline.yaml
- .tekton/lifecycle-agent-operator-bundle-4-20-pull-request.yaml
- .tekton/lifecycle-agent-operator-bundle-4-20-push.yaml
- OLM Bundle images must not be multi arch, per new Konflux policy
- Because Konflux said so
- Create parameter to allow setting image-append-platform to false just for bundle
- 
- Adding a new parameter to the pipeline
- Configure the parameter for the bundle
> Conform to new Konflux policy

- .konflux/overlay/overlay.bash
> Fix overlay.bash bug that would cause FBC problems later

- .konflux/konflux_build_args.conf
- Dockerfile
quay.io is not a good source for oc cli as it is not an official build
conforma policy does not allow us to use quay.io/openshift/* as a source image
- Use the production oc cli image to fetch the oc binary
- when 4.19 is released we should come back and update the tag here from v4.18 to v4.19
> Update to more acceptable openshift cli image

- .konflux/konflux_build_args.conf
- Dockerfile
quay.io is not a good source for oc cli as it is not an official build
conforma policy does not allow us to use quay.io/openshift/* as a source image
- Use the production oc cli image to fetch the oc binary
- when 4.19 is released we should come back and update the tag here from v4.18 to v4.19
> [release-4.19] Update to more acceptable openshift cli image

- .tekton/lifecycle-agent-4-20-pull-request.yaml
- .tekton/lifecycle-agent-4-20-push.yaml
- .tekton/lifecycle-agent-operator-bundle-4-20-pull-request.yaml
- .tekton/lifecycle-agent-operator-bundle-4-20-push.yaml
- Update the taskRunTemplate to the new service account
- Konflux was supposed to migrate this automatically, but the bot is including more changes besides just this
> Konflux build configuration updates

- .tekton/lifecycle-agent-4-19-pull-request.yaml
- .tekton/lifecycle-agent-4-19-push.yaml
- .tekton/lifecycle-agent-operator-bundle-4-19-pull-request.yaml
- .tekton/lifecycle-agent-operator-bundle-4-19-push.yaml
- Update the taskRunTemplate to the new service account
- Konflux was supposed to migrate this automatically, but the bot is including more changes besides just this
> [release-4.19] Konflux build configuration updates

- .konflux/overlay/overlay.bash
> Fix typo and add url comment

- .konflux/overlay/overlay.bash
> [release-4.19] Fix typo and add url comment

- .konflux/overlay/overlay.bash
> Fix errant bracket

- .konflux/overlay/overlay.bash
> Update LCA overlay to insert recert to manager environment

- .konflux/overlay/overlay.bash
> [release-4.19] Fix errant bracket

- .konflux/overlay/overlay.bash
> [release-4.16] Fix missing quotes in yq replaces line

- .konflux/overlay/overlay.bash
> [release-4.17] Fix missing quotes in yq replaces line

- .konflux/overlay/overlay.bash
> [release-4.18] Fix missing quotes in yq replaces line

- .konflux/overlay/overlay.bash
> Fix missing quotes in yq replaces line

- .tekton/build-pipeline.yaml
> Update konflux tasks to latest

- .tekton/build-pipeline.yaml
- .tekton/lifecycle-agent-4-20-pull-request.yaml
- .tekton/lifecycle-agent-4-20-push.yaml
- .tekton/lifecycle-agent-operator-bundle-4-20-pull-request.yaml
- .tekton/lifecycle-agent-operator-bundle-4-20-push.yaml
> Add `latest` tag to quay builds

- .konflux/overlay/overlay.bash
- .konflux/overlay/pin_images.in.yaml
- renovate.json
- Add missing tag
- Update digest
> [release-4.16] Fix kube rbac proxy pinning

- .konflux/Dockerfile.catalog
- .konflux/container_build_args.conf
- .tekton/fbc-pipeline.yaml
- .tekton/lifecycle-agent-fbc-4-17-pull-request.yaml
- .tekton/lifecycle-agent-fbc-4-17-push.yaml
- Makefile
- bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
- config/manifests/bases/lifecycle-agent.clusterserviceversion.yaml
> [release-4.17] Catalog configuration for 4.17

- .konflux/overlay/overlay.bash
- The data here has been retrieved from the existing 4.18 catalog
> [release-4.19] Align overlay contents with data used in previous releases

- .konflux/overlay/overlay.bash
- The data here has been retrieved from the existing 4.18 catalog
> [release-4.16] Align overlay contents with data used in previous releases

- .konflux/overlay/map_images.in.yaml
- .konflux/overlay/pin_images.in.yaml
> Fix bundle overlay for recert

- .tekton/build-pipeline.yaml
- .tekton/fbc-pipeline.yaml
Reverts openshift-kni/lifecycle-agent#1181
> Revert "Update Konflux references"

- .konflux/overlay/overlay.bash
- Makefile
> [release-4.19] Prepare for 4.19.1 

- .konflux/Dockerfile.catalog
- .konflux/container_build_args.conf
> Fix opm image in use

- .konflux/overlay/map_images.in.yaml
- OCP 4.14 does not use rhel9 for this image
> [release-4.14] Fix incorrect image name for kube rbac proxy mapping

- .konflux/catalog/fbc-images-resolvable-integration-test-idms.yaml
> Add new IDMS configuration to use for integration tests

- .tekton/lifecycle-agent-fbc-4-20-pull-request.yaml
- .tekton/lifecycle-agent-fbc-4-20-push.yaml
- We need to build an arm64 FBC for QE to test with
- Updated comments to reflect current state
> Make the LCA FBC multi arch

- .konflux/Dockerfile.catalog
- .konflux/container_build_args.conf
- We don't want to use an unreleased build for the next z stream ship
> Update to use released opm image for 4.19

- .konflux/overlay/overlay.bash
- The min_kube_version needs to be set using three field semantic versioning, e.g. x.y.z
> [release-4.15] OCPBUGS-59548: Fix min_kube_version for LCA bundle

- .konflux/overlay/overlay.bash
- The min_kube_version needs to be set using three field semantic versioning, e.g. x.y.z
> [release-4.14] OCPBUGS-59548: Fix min_kube_version for LCA bundle

- .konflux/overlay/overlay.bash
- The min_kube_version needs to be set using three field semantic versioning, e.g. x.y.z
> [release-4.16] OCPBUGS-59548: Fix min_kube_version for LCA bundle

- .konflux/overlay/overlay.bash
- The min_kube_version needs to be set using three field semantic versioning, e.g. x.y.z
> [release-4.17] OCPBUGS-59548: Fix min_kube_version for LCA bundle

- Makefile
> [release-4.18] Fix version used for catalog compare

- Makefile
> [release-4.17] Fix version used for catalog compare

- .ci-operator.yaml
- .konflux/Dockerfile.catalog
- .konflux/container_build_args.conf
- Dockerfile
- go.mod
- internal/backuprestore/common.go
- internal/extramanifest/extramanifest.go
- internal/healthcheck/healthcheck.go
- lca-cli/cmd/create.go
- lca-cli/cmd/ibuStaterootSetup.go
> Upversion golang to 1.24

- .ci-operator.yaml
- .github/dependabot.yml
- .golangci.yml
- .konflux/catalog/fbc-images-resolvable-integration-test-idms.yaml
- .konflux/lock-runtime/rpms.in.yaml
- .konflux/lock-runtime/rpms.lock.yaml
- .konflux/overlay/map_images.in.yaml
- .konflux/overlay/pin_images.in.yaml
- .markdownlint-cli2.yaml
- .tekton/build-pipeline.yaml
- .tekton/fbc-pipeline.yaml
- .tekton/images-mirror-set.yaml
- .tekton/lifecycle-agent-4-20-pull-request.yaml
- .tekton/lifecycle-agent-4-20-push.yaml
- .tekton/lifecycle-agent-fbc-4-20-pull-request.yaml
- .tekton/lifecycle-agent-fbc-4-20-push.yaml
- .tekton/lifecycle-agent-operator-bundle-4-20-pull-request.yaml
- .tekton/lifecycle-agent-operator-bundle-4-20-push.yaml
- .testcoverage.yml
- .yamllint.yaml
- hack/yamllint.sh
- Without extending any existing ruleset we were effectively running yamllint with an empty configuration
- Fix the configuration, and then fix all the yamllint warnings newly exposed
> Update yamllint configuration and fix warnings

- .ci-operator.yaml
- .github/dependabot.yml
- .golangci.yml
- .konflux/catalog/catalog-template.in.yaml
- .konflux/catalog/fbc-images-resolvable-integration-test-idms.yaml
- .konflux/lock-runtime/rpms.in.yaml
- .konflux/lock-runtime/rpms.lock.yaml
- .konflux/overlay/map_images.in.yaml
- .konflux/overlay/pin_images.in.yaml
- .markdownlint-cli2.yaml
- .tekton/build-pipeline.yaml
- .tekton/fbc-pipeline.yaml
- .tekton/images-mirror-set.yaml
- .tekton/lifecycle-agent-4-18-pull-request.yaml
- .tekton/lifecycle-agent-4-18-push.yaml
- .tekton/lifecycle-agent-fbc-4-18-pull-request.yaml
- .tekton/lifecycle-agent-fbc-4-18-push.yaml
- .tekton/lifecycle-agent-operator-bundle-4-18-pull-request.yaml
- .tekton/lifecycle-agent-operator-bundle-4-18-push.yaml
- .testcoverage.yml
- .yamllint.yaml
- hack/yamllint.sh
- Update .yamllint.yaml configuration
- Fix linter warnings in linted files
> (release-4.18) Backport linter configuration and fixes

- .yamllint.yaml
> Add yamllint key to yamllint configuration

- .konflux/Dockerfile.catalog
- Makefile
- Define versions for all tools downloaded
- Make use of new download-go-tool script for several features
- Update telco5g-konflux subproject to latest commit
> Update project makefile to improve shared library script usage

- .konflux/Dockerfile.catalog
- Makefile
> [release-4.16] Update project makefile to improve shared library script usage 

- .konflux/Dockerfile.catalog
- Makefile
> [release-4.14] Update project makefile to improve shared library script usage 

- .konflux/Dockerfile.catalog
- Makefile
Some additional updates to improve the robustness of the makefile
> Makefile robustness updates

- .tekton/build-pipeline.yaml
- .yamllint.yaml
- Makefile
Assisted-by: Cursor/claude-4-sonnet
AI-attribution: AIA,Human-AI blend,Human-initiated,Reviewed,Cursor/claude-4-sonnet,v1.0
For more information on AI attribution statements, see: https://aiattribution.github.io/
> CNF-18558: Fix sed to work more reliably on the dockerfile edits

- .tekton/build-pipeline.yaml
- .tekton/lifecycle-agent-4-17-pull-request.yaml
- .tekton/lifecycle-agent-4-17-push.yaml
- .tekton/lifecycle-agent-fbc-4-17-pull-request.yaml
- .tekton/lifecycle-agent-fbc-4-17-push.yaml
- .tekton/lifecycle-agent-operator-bundle-4-17-pull-request.yaml
- .tekton/lifecycle-agent-operator-bundle-4-17-push.yaml
- Backport https://github.com/openshift-kni/lifecycle-agent/pull/2624
- Backport https://github.com/openshift-kni/lifecycle-agent/pull/2670
> [release-4.17] Konflux Backports

- .tekton/build-pipeline.yaml
- .tekton/lifecycle-agent-4-18-pull-request.yaml
- .tekton/lifecycle-agent-4-18-push.yaml
- .tekton/lifecycle-agent-fbc-4-18-pull-request.yaml
- .tekton/lifecycle-agent-fbc-4-18-push.yaml
- .tekton/lifecycle-agent-operator-bundle-4-18-pull-request.yaml
- .tekton/lifecycle-agent-operator-bundle-4-18-push.yaml
- Backport https://github.com/openshift-kni/lifecycle-agent/pull/2624
- Backport https://github.com/openshift-kni/lifecycle-agent/pull/2670
> [release-4.18] Konflux Backports

- .konflux/lock-runtime/rpms.in.yaml
- .konflux/lock-runtime/rpms.lock.yaml
- Backport of https://github.com/openshift-kni/lifecycle-agent/pull/2679
> [release-4.14] CNF-19739: Add missing EUS repos to rpm lock configuration

- .konflux/lock-runtime/rpms.in.yaml
- .konflux/lock-runtime/rpms.lock.yaml
- Backport of https://github.com/openshift-kni/lifecycle-agent/pull/2679
> [release-4.18] CNF-19739: Add missing EUS repos to rpm lock configuration
